### ISSUE TITLE
RGB colorpicker 2 not working

### ISSUE THREAD

**Issue by svollebregt** [Dashticz/dashticz#1000]
Hi all,

I recently added an RGB switch to my Dashtics. The old colorpicker works, but when I select colorpicker 2 I get the following exception in Chrome:

bundle.js?t=47:309 jQuery.Deferred exception: el.modal is not a function TypeError: el.modal is not a function
    at js/colorpicker.js:240:8
    at mightThrow (http://rpi-mon.lan/dashticz/dist/bundle.js?t=47:309:28935)
    at le (http://rpi-mon.lan/dashticz/dist/bundle.js?t=47:309:29334) undefined
jQuery.Deferred.exceptionHook @ bundle.js?t=47:309
bundle.js?t=47:309 jQuery.Deferred exception: el.modal is not a function TypeError: el.modal is not a function
    at js/colorpicker.js:240:8
    at mightThrow (http://rpi-mon.lan/dashticz/dist/bundle.js?t=47:309:28935)
    at le (http://rpi-mon.lan/dashticz/dist/bundle.js?t=47:309:29334) undefined
jQuery.Deferred.exceptionHook @ bundle.js?t=47:309

No pop-up window appears and I cannot set the color. Anyone any idea what causes this?

**Comment by lokonli** [comment]
It's working on my system.
What's your Dashticz version?

**Comment by svollebregt** [comment]
I am running v3.9.5. beta on a sell-installed apache running on an RPi using the manual setup instructions with PHP 7.31.1.

**Comment by lokonli** [comment]
Can you test latest Dashticz beta version?

**Comment by svollebregt** [comment]
Sorry for the late reply. I moved and it took a while to get everything up and running. When I try to push the menu pulldown button on the colorpicker I get the following error in Chrome with the latest beta:
`bundle.js?t=61:309 jQuery.Deferred exception: el.modal is not a function TypeError: el.modal is not a function
    at js/colorpicker.js:240:8
    at mightThrow (http://rpi-mon.lan/dashticz/dist/bundle.js?t=61:309:28935)
    at le (http://rpi-mon.lan/dashticz/dist/bundle.js?t=61:309:29334) undefined`

**Comment by lokonli** [comment]
Which Dashticz version are you using at the moment?
How did you define the block in CONFIG.js?
Can you post a screenshot of the rgb switch in Dashticz? (via Windows knipprogramma you can copy/paste it here)

**Comment by svollebregt** [comment]
I am currently running v3.10.0.2 beta, but the problem still persists.

I define the block as:
`
blocks[31] = {
        title: 'RGB',
        width: 4,
        last_update: false
}`

And this is what it looks like:
![Screenshot 2023-01-28 134803](https://user-images.githubusercontent.com/42436341/215267242-3bea2aa4-3d88-4547-a816-01ca162af4ba.jpg)

**Comment by lokonli** [comment]
I can't reproduce the problem :(

You are using Chrome on Windows, or something else?
If on Windows, can you press F12 to open DevTools, refresh Dashticz.
Do you see on the console tab in DevTools any other error?

**Comment by svollebregt** [comment]
This is what I get after a refresh:

>DevTools failed to load source map: Could not load content for chrome-extension://idnomlffdbadkainngpiabkecmapeaad/js/libs/underscore-min.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://idnomlffdbadkainngpiabkecmapeaad/js/libs/backbone-min.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://idnomlffdbadkainngpiabkecmapeaad/js/libs/purify.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for http://rpi-mon.lan/dashticz/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
version.js:112 Not able to parse Domoticz build number:  2022.2
version.js:147 Domoticz version:  {build: 0, version: 2022.2, levelNamesEncoded: true, newBlindsBehavior: true}
domoticz-api.js:125 Setting up websocket
domoticz-api.js:190 [open] Connection established
janus.js:278 Initializing library
janus.js:450 Library initialized: true
janus.js:473 Using REST API to contact Janus: http://rpi-mon.lan:8088/janus
janus.js:946 Created session: 1562394857775022
janus.js:1280 Created handle: 1827160136395308
streamingtest.js:81 Plugin attached! (janus.plugin.streaming, id=1827160136395308)
janus.js:1446 Synchronous transaction successful (janus.plugin.streaming)
streamingtest.js:278 Got a list of available streams
app.min.js?v=1655544412:24 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
c @ app.min.js?v=1655544412:24
B @ app.min.js?v=1655544412:24
q @ app.min.js?v=1655544412:24
K @ app.min.js?v=1655544412:24
(anonymous) @ app.min.js?v=1655544412:141
is @ app.min.js?v=1655544412:95
bc @ app.min.js?v=1655544412:95
t.unstable_runWithPriority @ app.min.js?v=1655544412:103
Hi @ app.min.js?v=1655544412:95
mc @ app.min.js?v=1655544412:95
Zs @ app.min.js?v=1655544412:95
(anonymous) @ app.min.js?v=1655544412:95
t.unstable_runWithPriority @ app.min.js?v=1655544412:103
Hi @ app.min.js?v=1655544412:95
Gi @ app.min.js?v=1655544412:95
Yi @ app.min.js?v=1655544412:95
Ks @ app.min.js?v=1655544412:95
enqueueSetState @ app.min.js?v=1655544412:95
_.setState @ app.min.js?v=1655544412:87
(anonymous) @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:1
xn @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
Promise.then (async)
(anonymous) @ app.min.js?v=1655544412:141
Promise.then (async)
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
persist @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
n @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:79
n @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:1
app.min.js?v=1655544412:24 [react-ga] ReactGA.initialize must be called first or GoogleAnalytics should be loaded manually
c @ app.min.js?v=1655544412:24
B @ app.min.js?v=1655544412:24
q @ app.min.js?v=1655544412:24
X @ app.min.js?v=1655544412:24
(anonymous) @ app.min.js?v=1655544412:141
is @ app.min.js?v=1655544412:95
bc @ app.min.js?v=1655544412:95
t.unstable_runWithPriority @ app.min.js?v=1655544412:103
Hi @ app.min.js?v=1655544412:95
mc @ app.min.js?v=1655544412:95
Zs @ app.min.js?v=1655544412:95
(anonymous) @ app.min.js?v=1655544412:95
t.unstable_runWithPriority @ app.min.js?v=1655544412:103
Hi @ app.min.js?v=1655544412:95
Gi @ app.min.js?v=1655544412:95
Yi @ app.min.js?v=1655544412:95
Ks @ app.min.js?v=1655544412:95
enqueueSetState @ app.min.js?v=1655544412:95
_.setState @ app.min.js?v=1655544412:87
(anonymous) @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:1
xn @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
Promise.then (async)
(anonymous) @ app.min.js?v=1655544412:141
Promise.then (async)
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:141
b @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
persist @ app.min.js?v=1655544412:141
(anonymous) @ app.min.js?v=1655544412:141
n @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:79
n @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:1
(anonymous) @ app.min.js?v=1655544412:1
app.min.js?v=1655544412:24          GET https://www.google-analytics.com/analytics.js net::ERR_CERT_AUTHORITY_INVALID

And this appears when I try to expand the button:
> bundle.js?t=63:309 jQuery.Deferred exception: el.modal is not a function TypeError: el.modal is not a function
    at js/colorpicker.js:240:8
    at mightThrow (http://rpi-mon.lan/dashticz/dist/bundle.js?t=63:309:28935)
    at le (http://rpi-mon.lan/dashticz/dist/bundle.js?t=63:309:29334) undefined

The Janus messages are because I use the custom HTML block to embed a webRTC video stream. Could this embedded HTML block mess with the dependencies?

**Comment by lokonli** [comment]
Can you test a dashboard with only one RGB device?
You can create CONFIG.test.js in the custom folder, and load with:
http://rpi-mon.lan/dashticz/?cfg=CONFIG.test.js

and then check DevTools again.

**Comment by svollebregt** [comment]
With only the RGB it correctly expands the colour wheel. If I comment out the line that loads the custom HTML block it also works on my original dashboard.

So I apparently break something when loading the HTML. Could you advise if I am doing something wrong in the HTML file? My web coding 'skills' are from the time that CSS just became a thing...

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Janus WebRTC Client: Simple Streaming Demo</title>

</head>

<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/8.0.0/adapter.min.js" ></script>
<script type="text/javascript" src="http://192.168.1.141/dashticz/custom/janus.js" ></script>
<script type="text/javascript" src="http://192.168.1.141/dashticz/custom/streamingtest.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js"></script>

        <div id="streams">
                <button id="watch">Wait..</button>
                <div>
                        <div id="stream"></div>
                </div>
        </div>
</body>
</html>

**Comment by lokonli** [comment]
I see you load jquery, but Dashticz also loads jQuery, and installs color picker on top of it.
So you have to remove the jQuery line.

I see you load some javascript as part of head and a second time as part of body. That's not good. You can remove the parts from body that you already loaded in head.

**Comment by svollebregt** [comment]
Thanks, removing the jQuery line indeed resolves it. The script loading lines in the head are commented out, this was from an earlier iteration that did not work properly.
