### ISSUE TITLE
Enable the use of variables in graphs to create offset, scaling or other maniplation

### ISSUE THREAD

**Issue by brjhaverkamp** [Dashticz/dashticz#1003]
As described in https://www.domoticz.com/forum/viewtopic.php?t=39205&sid=70ff0e3050c8bcc5b1debd40866033ff
it would be good to have a way to use a constant, coming from a domoticz device or variable to manipulate graph data.
In my case simply to get rid of an offset. But changing the magnitude of a graph by a scaling factor could also be a usecase.

It is currently already possible to subtract a number from the graph in the data definition.
My request is to have this "number" come from a variable or device in domoticz.
```
"last year": {
            range: 'year',
            filter: '12 months',
            data: {
                G: 'd.c_3-11152.95',
                E: 'd.c1_1-d.c3_1+d.c2_1-d.c4_1+301.98',
                L: 'd.c1_1-d.c3_1-1867.56',
                H: 'd.c2_1-d.c4_1+2183.53',
            },
            ylabels: ['m³ or kWh'],
        }
```

**Comment by lokonli** [comment]
Solution described in:
https://www.domoticz.com/forum/viewtopic.php?p=293826#p293826
