### ISSUE TITLE
Add "displayhidden" config

### ISSUE THREAD

**Issue by MiloshCZ** [Dashticz/dashticz#1008]
Hi,
I have lots of devices hidden in domoticz (name starting with "$"). Is it possible to add config option to show "hidden" devices. Hidden devices are not visible in json by default, it is neccessary add "displayhidden=1" option to html request

https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Get_status_of_all_devices.2C_including_hidden_ones

for examle as config option:
config['use_hidden'] = '1';

Thank you

**Comment by lokonli** [comment]
Implemented with #1012 in latest beta. Can you test?

**Comment by MiloshCZ** [comment]
Hi,
thank you, it is working now
