### ISSUE TITLE
Selector Switch ipadOS16

### ISSUE THREAD

**Issue by azsystem** [Dashticz/dashticz#1014]
With this update, the selector switch is showing no options/buttons, just empty.
This happens on ipad os 16

**Comment by lokonli** [comment]
What is your Domoticz version? 
Dashticz version?

Do you have config['use_favorites'] = 1 in your config.js? Then remove that line, or mark your selector switch as favorite in Domoticz.

**Comment by azsystem** [comment]
Domoticz: 2022.2
Dashticz: 3.9.4 = OK, 3.9.6.1 has the issue. So now I'm running 3.9.4.

I don't have config['use_favorites'] in the config.js. 
The selector switch is set to favorites in Domoticz.

The issue also happens on iPadOs 15.

**Comment by lokonli** [comment]
In 3.9.6 there are some changes in the mechanism to detect the Domoticz version (to be able to handle the new blinds behavior in Domoticz). Probably I introduced a bug.

Can you help with debugging?
If you have a desktop, open Dashticz there, press F12 to open DevTools, refresh Dashticz.
In the DevTools console tab, click on User Messages. Then in the window you see a message 'Domoticz version' followed by an object. Can you post the content of this object? (build: xxx, levelNamesEncoded: ..., newBlindsBehavior: ..., version: ...)

**Comment by lokonli** [comment]
Be sure to update to latest version via git pull.

**Comment by azsystem** [comment]
Seems to be fixed in 3.9.7.
Thank you.

Do you still want me to provide some debug info?
If so, which browser do you prefer?

**Comment by lokonli** [comment]
Great!

No need to test anymore.

I realized I made an additional fix after creating the 3.9.6.1 release. So I created a new version 3.9.7 containing the latest fixes.

I'll close this issue now.
