### ISSUE TITLE
Blinds + Stop not supported

### ISSUE THREAD

**Issue by Domotixz** [Dashticz/dashticz#1020]
Why is it that blinds + stop is not supported? When the domoticz switchtype is set to this type dashticz shows a bulb. When settings domoticz to blinds, dashticz shows the stop button but there is no stop button in domoticz. So to have the stop button in dashticz i have to remove it in domoticz!? Why is that?

**Comment by lokonli** [comment]
What is your Dashticz version?
And your Domoticz version?

This should be supported from Dashticz 3.9.6 and higher.

**Comment by Domotixz** [comment]
i just moved to latest dashticz and latest domoticz. still not supported.

**Comment by lokonli** [comment]
What is your Dashticz version?(click in Dashticz on the Settings icon, upper right, then on the info tab)

How did you define your blinds block in CONFIG.js? Can you post that here?

**Comment by Domotixz** [comment]
<img width="271" alt="Schermafbeelding 2022-12-19 om 10 25 07" src="https://user-images.githubusercontent.com/117913713/208392402-8cfac2df-7185-4c58-9dad-13a4aa3bfdeb.png">

config block for blinds => 

blocks['Blinds_1'] = {
        idx: 4749,
        width: 6,
        title: 'Raam'
}

**Comment by lokonli** [comment]
You were using the master branch, version 3.9
The fix was implemented in the beta branch, version 3.9.6

In the mean time a new master version has been released (3.10). You can switch to that version.
