### ISSUE TITLE
Dial 'Wind' offset parameter not working

### ISSUE THREAD

**Issue by Losje** [Dashticz/dashticz#1032]
The Wind dial is not changing when setting the offset parameter to 180.

I've tried a clean install of dashticz, using the example code from the manual.

Full config on clean install:

```
var config = {}
config['domoticz_ip'] = 'http://192.168.55.87:8080';
config['app_title'] = 'Dashticz V3';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';

config['translate_windspeed'] = 1;

blocks['wind'] = {
  idx: 175,
  type: 'dial',
  offset: 180,  // 0 will point to the wind source, 180 will point to wind direction (default is 0)
  width: 6,
}

//Definition of columns
columns = {}
columns[1] = {
  blocks : ['wind'],
  width: 4
}

//Definition of screens
screens = {}
screens[1] = {
  columns: [1]
}
```

System setup: 
Dashticz and Domoticz running on same Raspberry Pi
Dashticz version 3.10.0.1
Domoticz version 2022.2

Wind info coming from Open Weather Map device in Domoticz. 
Needle is always pointing in the direction where the wind is coming from, regardless of setting offset to 180 / 0.

**Comment by lokonli** [comment]
Fixed in 3.10.0.2
