### ISSUE TITLE
blinds open/close error 

### ISSUE THREAD

**Issue by Levynger** [Dashticz/dashticz#105]
Dashticz V3.1.2, suing automated installation.

I have blind type switch in domoticz 
the slider works well, 
however the Open/Close buttons - produces errors:

> Uncaught TypeError: Cannot read property 'replace' of undefined

    at switchBlinds (eval at globalEval (jquery.min.js:2), <anonymous>:92:57)
    at HTMLAnchorElement.onclick ((index):1)
    switchBlinds @ VM450:92
    onclick @ (index):1

**Comment by lokonli** [comment]
I'll test later this week.

**Comment by lokonli** [comment]
Did you maybe set a custom icon or image for the blinds block?
Can you post your block definition here?

**Comment by lokonli** [comment]
Should be fixed in latest beta. Can you test?

**Comment by lokonli** [comment]
Solved in beta v3.2.0

**Comment by Levynger** [comment]
sorry for late response, was rough weekend :)
i have updated the from git, indeed it seems to be fixed!!
 still investigating what the 'stops' button sends through mqtt - as im using node-red to translate the domoticz/out for my shelly2 roller shutter (official firmware)

thanks !!
