### ISSUE TITLE
Dial: P1 usage (Today) regression in 3.10.1

### ISSUE THREAD

**Issue by Losje** [Dashticz/dashticz#1051]
After installing beta 3.10.1 the actual power in Watts is shown in the P1 dial instead of the usage in kWh.
This is different according to the manual, expected behavior:
https://dashticz.readthedocs.io/en/master/_images/dial_p1-meter-cons.jpg

Same result while using the exact example from the manual.

The needle also indicated the actual Watts instead of usage.

**Comment by Losje** [comment]
This seems to be the issue:
https://github.com/Dashticz/dashticz/pull/1037/commits/ce1c41c5ce36f3d1c1dbedb1acc05aecff966b10

It appears to be a feature that has been implemented, but i think this should be configurable?

**Comment by lokonli** [comment]
Thanks for reporting.

I'll make it configurable.

**Comment by Losje** [comment]
Great! Thanks for the quick response.

**Comment by lokonli** [comment]
Solved with #1054 Dashticz 3.10.2 beta

**Comment by Losje** [comment]
Working now as expected; thanks fo resolving quickly and reverting the default to the original behavior
