### ISSUE TITLE
Icon does not appear

### ISSUE THREAD

**Issue by zerr0s** [Dashticz/dashticz#1063]
Hello,

I'm trying to use the fa-engine icon from awesome. This icon does not appear.

`<i class="fa-regular fa-engine"></i>`

Is there a way to use this icon please ??

Thanks.

**Comment by lokonli** [comment]
fa-engine is not part of the free font-awesome icon set. That means you can't use it.

**Comment by zerr0s** [comment]
ok, thanks :)
