### ISSUE TITLE
decoding switch string base64 

### ISSUE THREAD

**Issue by pfolcato** [Dashticz/dashticz#1084]
Hi, I update domoticz to version 2023.2 and dashticz show me the string of switch encoded in base64 
![immagine](https://github.com/Dashticz/dashticz/assets/74878466/77751988-7a76-4ffb-acc2-1d956dd2b39d)
I found a threat of the same old issue but still not working for me
https://github.com/Dashticz/dashticz_v2/issues/369

**Comment by lokonli** [comment]
Which Dashticz version are you using?
Try latest Dashticz master or beta version.

**Comment by pfolcato** [comment]
Beta version work! thanks!
