### ISSUE TITLE
Buienradar blocks iframes now

### ISSUE THREAD

**Issue by aalwash** [Dashticz/dashticz#11]
Buienradar.nl added a X-Frame-Options: Deny, causing the iframe to be blocked

`Refused to display 'https://www.buienradar.nl/weer/den_haag/nl/2747373' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Proposed solution:**
Open Buienradar.nl URL in a new tab

What do you guys think?
Could be annoying on a tablet, but there isnt' much of a solution
Of course you can proxy the content, but that's a lot of hassle for just opening a buienradar page

**Comment by lokonli** [comment]
Met proxy werkt het:

    frameurl: './vendor/dashticz/cors.php?https://www.buienradar.nl/weer/den_haag/nl/2747373',

Het is niet moeilijk om een optie 'useProxy' aan de block definitie toe te voegen, en vervolgens het CORS_PATH voor de frameurl te plakken.

Je kan ook een alternatieve url gebruiken, bv:

frameurl:'https://gadgets.buienradar.nl/gadget/zoommap/?lat=51.3578&lng=6.17428&overname=2&zoom=8&naam=5912TN&size=3&voor=1',

of:
    frameurl:'http://api.buienradar.nl/image/1.0/RadarMapNL?w=360&h=300',

**Comment by aalwash** [comment]
I will use the CORS solution
