### ISSUE TITLE
Dial, thermostat setpoint+temp : unable to change dialicon in updown subtype  

### ISSUE THREAD

**Issue by pquinqu** [Dashticz/dashticz#1111]
in CUSTOM.js file, declaring
  blocks[36] = { temp: 47, type: 'dial', subtype: 'updown', dialicon: 'fas fa-thermostat-half' }
doesn't change the calendar fas icon to the new one

The issue is located in the file components/dial.js, function valueUpDown(me)
Original code is
      return ''+number_format(me.temp,1) + _TEMP_SYMBOL +'&nbsp; <em class="icon fas fa-calendar-alt"></em>&nbsp;' + number_format(me.setpoint,me.decimals) + me.unitvalue;

I suggest :
1- swapping setpoint and temperature as it appears more natural to have the setpoint first
2- also replacing _TEMP_SYMBOL by me.unitvalue
3- using me.dialicon as it can be overriden by CONFIG.js
Resulting code could be :
      return ''+ number_format(me.setpoint, me.decimals) + me.unitvalue +'&nbsp; <em class="icon ' + me.dialicon + '"></em>&nbsp;'+ number_format(me.temp,1) + me.unitvalue;

Regards.
Phil

**Comment by lokonli** [comment]
I'll have a look

**Comment by lokonli** [comment]
Implemented in latest beta.
I've made the order of the setpoint and temp device a block parameter.

You can show the setpoint first by adding the following block parameter:

```
    setpointfirst: true
```

Can you test?

**Comment by pquinqu** [comment]
Thanks, it's working fine.
