### ISSUE TITLE
Feature request: dialimage with css for url

### ISSUE THREAD

**Issue by Maikeleg** [Dashticz/dashticz#1114]
As explained here: https://www.domoticz.com/forum/viewtopic.php?t=40911

```
function getStatus_179(block) {                            //iconpath for music
  var idx10 = block.idx;
  var device10 = block.device;
     if (device10['Data'] != '') {                        //if image is available
         Dashticz.setBlock(180, {         //Music Dial
            dialimage: device10.Data     //<------- this one
         });
     } // end if
     else {                                                     //if image is empty
          Dashticz.setBlock(180, {         //Music Dial
            dialimage: ''
          });
     } //end if else
} // end funtion icon path music
```

This way I can use a dial as a music player
It would be awesome if I could use the value from the textfield, which is the imageurl, to display the image. 

PS: If I can do that when the dial main idx is a virtual switch so I can turn on/off play/pause the music it would be even more awesome.

**Comment by lokonli** [comment]
Check latest beta.

https://dashticz.readthedocs.io/en/beta/blocks/specials/dial.html#dial-background-image

**Comment by Maikeleg** [comment]
> Check latest beta.
> 
> https://dashticz.readthedocs.io/en/beta/blocks/specials/dial.html#dial-background-image

OMG this is so cool, thanks so much, I'm gonna try now.
Thanks Sander and team for all your work
