### ISSUE TITLE
Barometer device not showing any data

### ISSUE THREAD

**Issue by StefTan** [Dashticz/dashticz#1115]
Hello,

For my combined Temperature/barometer device:

![image](https://github.com/Dashticz/dashticz/assets/42466807/5b6e0d75-bd19-4cf4-aea2-ba058f798d7d)

I do not get any data visible in the graphs. The other deves are correctly showing Temperature and Huminity.

The URL Shown in the data section of debug is:

http://[My domotcz IP]/json.htm?type=command&param=graph&sensor=counter&idx=1224&range=day&method=1

Data Shown:

![image](https://github.com/Dashticz/dashticz/assets/42466807/373c6d0e-0497-4758-a9c0-dab21d19b597)

for a working device (Not Barometer) I get the url:

http://[My domotcz IP]/json.htm?type=command&param=graph&sensor=temp&idx=4952&range=day&method=1

So the Sensor name in de url is "temp" (instate of "counter" for the not working one) .

If I replace counter for temp in the not working URL and I get the correct results back from my barometer device as well.

If I want to graph barometer data I cannot access it.

Please check if it is a bug or it is my code:

Code: 
blocks['Temperatuur'] = {
        title: 'Temperatuur',
        debugButton: true,
        devices: [ 4931, 4372, 314, 4943 ,4952,4949,4950,374,369,1224],
        graphTypes: ['te'],
        graph: 'line',
        buttonsBorder: '#ccc',
        buttonsColor: '#ccc',
        buttonsFill: 'transparent',
        buttonsIcon: 'Blue',
        buttonsPadX: 10,
        buttonsPadY: 5,
        buttonsMarginX: 5,
        buttonsMarginY: 2,
        buttonsRadius: 0,
        buttonsShadow: 'rgba(2, 117, 216, 0.2)',
        buttonsSize: 12,
                custom : {
                        "Last hours": {
                                range: 'day',
                                filter: '6 hours',
                                data: {
                                        te_4931: 'd.te_4931',
                                        te_4372: 'd.te_4372',
                                        te_314: 'd.te_314',
                                        te_4943: 'd.te_4943',
                                        te_4952: 'd.te_4342',
                                        te_4949: 'd.te_4949',
                                        te_4950: 'd.te_4950',
                                        te_374: 'd.te_274',
                                        te_369: 'd.te_369',
				te_1224: 'd.te_1224'
                                },
                        },
                        "Last 2 weeks": {
                                range: 'month',
                                filter: '14 days',
                                data: {
                                        te_4931: 'd.te_4931',
                                        te_4372: 'd.te_4372',
                                        te_314: 'd.te_314',
                                        te_4943: 'd.te_4943',
                                        te_4952: 'd.te_4342',
                                        te_4949: 'd.te_4949',
                                        te_4950: 'd.te_4950',
                                        te_374: 'd.te_274',
                                        te_369: 'd.te_369',
				te_1224: 'd.te_1224'
                                }
                        },
                        "Last 6 months": {
                                range: 'year',
                                filter: '6 months',
                                data: {
                                        te_4931: 'd.te_4931',
                                        te_4372: 'd.te_4372',
                                        te_314: 'd.te_314',
                                        te_4943: 'd.te_4943',
                                        te_4952: 'd.te_4342',
                                        te_4949: 'd.te_4949',
                                        te_4950: 'd.te_4950',
                                        te_374: 'd.te_274',
                                        te_369: 'd.te_369',
				te_1224: 'd.te_1224'
                                }
                        }
                },
        legend: {
                'te_4931': 'Buiten',
                'te_4372': 'Woonkamer',
                'te_314': 'Badkamer',
                'te_4943': 'Werkkamer S..',
                'te_4952': 'Werkkamer W..',
                'te_4949': 'Strijkkamer',
                'te_4950': 'Slaapkamer',
                'te_374': 'ZolderN..i',
                'te_369': 'ZolderE..',
	      'te_1224': 'Barometer'
        },
 	customHeader: '"Buiten Temeratuur: " + devices[4931].Data',
	height: '300px'
}

**Comment by lokonli** [comment]
It's a bug.
(first time use of Temp + Baro device ...)

Thanks for the info: very usefull!

I've fixed it in latest beta. Can you test?
