### ISSUE TITLE
How to set up a custom diagram with double y axis

### ISSUE THREAD

**Issue by diegoflyer** [Dashticz/dashticz#1117]
How to set up a custom diagram with double y axis, I checked everywhere and not find a solution.
I would like to have te (temperature) data on one y axis and the other v data in an another one.
How can I do it?
Now I see no way with custom....

Here the code:

`
blocks['graph_boiler+termostati'] = {
    title: 'T-Boiler|Termostato',
    devices: [277,276,315,304,308,307],
    buttonsIcon: 'rgba(255,150,0,1)',
    buttonsBorder: 'rgba(255,150,0,1)',
    buttonsMarginX: 5,
    buttonsMarginY: 0,
    buttonsRadius: 10,
    datasetColors: ['rgba(255,70,0,1)','yellow','pink','rgba(255,255,255,0.6)','rgba(150,40,0,0.7)','rgba(0,170,255,1)'],
   graph: 'line',
   lineFill: [false,false,false,true,true,true],  
   height: '390px',
   buttonsIcon: 'rgba(255,150,0,1)',
   width: 12,
   cartesian: 'linear',//linear o logarithmic
   zoom: 'xy',
   
    custom : {
        "last day": {
            range: 'day',
            filter: '24 hours',
            graphTypes : ['te', 'v'],
            data: {
                TBoilerAlto: 'd.te_277',
                TBoilerBasso: 'd.te_276',
                TstartnoFV: 'd.te_315',
                PDC_ON: 'd.v_304',
                Recupero_PDC: 'd.v_308',
                Antilegionella: 'd.v_307',
            }
        },
        "last 2 weeks": {
            range: 'month',
            filter: '14 days',
            data: {
                TBoilerAlto: 'd.te_277',
                TBoilerBasso: 'd.te_276',
                TstartnoFV: 'd.te_315',
                PDC_ON: 'd.v_304',
                Recupero_PDC: 'd.v_308',
                Antilegionella: 'd.v_307',
            }
        },
        "last 6 months": {
            range: 'year',
            filter: '6 months',
            data: {
                TBoilerAlto: 'd.te_277',
                TBoilerBasso: 'd.te_276',
                TstartnoFV: 'd.te_315',
                PDC_ON: 'd.v_304',
                Recupero_PDC: 'd.v_308',
                Antilegionella: 'd.v_307',
            }
        }
    },
    legend: true,
}

`

**Comment by lokonli** [comment]
You can use the ylabels parameter, like:

```
    ylabels: ['temp', 'temp', 'temp', 'vdata', 'vdata', 'vdata'],
```

Also see:
https://dashticz.readthedocs.io/en/master/blocks/graphs.html?highlight=graphs#y-axis-for-custom-graphs

**Comment by diegoflyer** [comment]
Yhanks @lokonli  it works perfect, it was not clear to me how to use the documentation! Thanks! Diego
