### ISSUE TITLE
Dashticz freezed after standby without activity.

### ISSUE THREAD

**Issue by diegoflyer** [Dashticz/dashticz#1118]
HAving dashticz running on an Android Tablet I have the dashboard freezed after approx 40-50 minutes of inactivity.
Is there something to check on dashticz side or is it a settings in android?
I have the same with websocket enabled or not...

**Comment by lokonli** [comment]
I had similar issues with an old Android tablet. Normally the tablet became responsive again after a first touch.

I was not able to solve it. I suspect it's related to android memory management or JavaScript memory garbage collection, which I can't control via the app.

Try with high numbers for domoticz_refresh, dashticz_refresh, refresh parameters for cameras, graphs etcetera.

I solved it by buying a new, faster Android tablet.

**Comment by diegoflyer** [comment]
I bought a new one last year in order to solve the issue, surely it is improved but not completely solved. I had the same doubt (that the tablet specs was the trick) ... 
What are the minimum specs for your experience?

**Comment by lokonli** [comment]
I don't know what the minimum specs are. I use:
Teclast T40 Pro: 8GB Ram, T618 CPU. It works very well.

**Comment by diegoflyer** [comment]
ok thanks for the feedback, just for reference on my Lenovo Tab M10 Plus with 4 GB RAM with MediaTek Helio P22T (8C, 4x A53 2.3GHz 4x A53 1.8GHz) I have the dashboard freezed if no operation for a period.
When it is used it is not super fast but enough responsive.
