### ISSUE TITLE
Error creating HTML docs (beta version)

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#1122]
When trying to create HTML docs with lates betas I get the following error and the docs are not created:
```
Running Sphinx v1.8.4
loading translations [en]... done

Extension error:
Could not import extension sphinx_rtd_theme (exception: No module named sphinx_rtd_theme)
make: *** [Makefile:19: html] Error 2
```
With latest master version it is still working.

**Comment by lokonli** [comment]
The readthedocs site changed their build process. I had to update to a newer sphinx version, but that doesn't include the sphinx_rtd_theme by default.

I'll check how to update and let you know.

**Comment by lokonli** [comment]
Update to latest beta.

Then in the Dashticz folder:
```
cd docs
pip3 install -r requirements.txt
make clean
make html
```
