### ISSUE TITLE
Thermostat Dashticz block not showing correctly since Domoticz 2024.1

### ISSUE THREAD

**Issue by keesdekraker** [Dashticz/dashticz#1138]
After updating Domoticz to 2024.1, the thermostat block in Dashticz is shown as a (regular) switch (On/Off) device, instead of a thermostat/setpoint block.

I'm running Dashticz v3.11.

**Comment by lokonli** [comment]
This already has been fixed in latest beta (3.11.1) Can you test?

**Comment by keesdekraker** [comment]
Just tested latest beta. Working correctly again. Thnx!
