### ISSUE TITLE
apostrophe in weather location block dashticz

### ISSUE THREAD

**Issue by benoitjy** [Dashticz/dashticz#1139]
I work with V3.11.1 beta
I have a apostrophe in my village name. When i put it on the openweathermap parameter, dashticz save 'as it' in the CONFIG.js. And it blocks
If i put \ before apostrophe directly in the file, it works. 
Perhaps an oversight on saving filtering, with something like "mysql_real_escape_string" for json?

**Comment by lokonli** [comment]
Good catch.

Fixed in latest beta.
