### ISSUE TITLE
Watermeter (smartgateways.nl) supported?

### ISSUE THREAD

**Issue by rayray4105** [Dashticz/dashticz#1156]
Hi,

In my Domoticz I have connect a smartgateway / watermeter. If I use as simple block in Dashticz it will show todays water usage and the total amount of used water.

However when I try to show the watermeter as a dial (like my P1 or SolarEdge) then it will only show the total amount (not today's water usage). Is there a way to show today's water usage like the current energy consumption (for example)?

regards,
Raymond

**Comment by lokonli** [comment]
I expect that Domoticz reports the daily usage as well. You can set the device field that should be used in the dial via the 'value' block parameter in the block definition.

**Comment by rayray4105** [comment]
Thank you very much. I retrieved the correct value parameter from the graph data. Working like a charm now!
