### ISSUE TITLE
Bug with domoticz V2024.4 : Not able to parse Domoticz build number:  2024.4

### ISSUE THREAD

**Issue by JRB202** [Dashticz/dashticz#1158]
in /dashticz/js/domoticz-api.js 
with last domoticz version 2024.4

The function below is generating message in Chrome F12 console : 'Not able to parse Domoticz build number:  2024.4'
and sockets are not recognized then retrograding to http protocol

  function handleVersion(data) {
    info.version = parseFloat(data.version);
    $('#domoticz_version').html(info.version);

    try {
      info.build = parseInt(data.version.match(/build (\d+)(?=\))/)[1]);
    }
    catch (e) {
      console.log('Not able to parse Domoticz build number: ', data.version);
    }
    $('#dzvents_version').html(data.dzvents_version);
    $('#python_version').html(data.python_version);
    setDomoBehavior();
  }

Domoticz version information visible in Console is :

Domoticz version info:  
{build: 0, version: 2024.4, levelNamesEncoded: true, newBlindsBehavior: true, basicAuthRequired: true, …}
api15330: true
basicAuthRequired: true
build: 0
levelNamesEncoded: true
newBlindsBehavior: true
version: 2024.4

**Comment by JRB202** [comment]
I think the problem comes from a change in domoticz security described here :
https://www.domoticz.com/wiki/Security#API_Protection
where you can read :
NOTE: API URLs with username and password as parameters (eg https://IP:PORT/json.htm?username=userBASE64&password=PWDBASE64& ) are not supported anymore!
Use https://username:password@IP:PORT/json.htm instead

And in domoticz-api.js at line 362
I find :
usrinfo = 'username=' + cfg.usrEnc + '&password=' + cfg.pwdEnc + '&';

this is clearly generation of the unsupported syntax : username=userBASE64&password=PWDBASE64&

Code must be urgently changed to syntax : username:password@IP:PORT/json.htm

**Comment by lokonli** [comment]
Since Domoticz 2024.1 the address (or subnet) of the device that runs Dashticz should be whitelisted in Domoticz security settings. 
Can you check this?

**Comment by JRB202** [comment]
Whitelisting already defined as 127.0.0.*;192.168.*.*

Did you read this from domoticz forum site :
NOTE: API URLs with username and password as parameters (eg https://ip:PORT/json.htm?username=userBASE64&password=PWDBASE64& ) are not supported anymore!
Use https://username:password@ip:PORT/json.htm instead

dashticz code must be urgently changed to syntax : username:password@IP:PORT/json.htm

**Comment by lokonli** [comment]
Try with whitelisting set to: 127.0.0.;192.168.* or 127.0.0.;192.168.*.*
(the double point in your post is wrong)

The new authentication mechanisms have been impemented in Dashticz already.
For backwards compatiblity reasons the old basic authentication method is supported as well.

You are probably using a Domoticz master version. Domoticz then doesn't have a build number. This explains the log message you see. The behavior is correct.

Dashticz derives the following version dependent settings:
```
api15330: true
basicAuthRequired: true
build: 0
levelNamesEncoded: true
newBlindsBehavior: true
version: 2024.4
```

There are correct.

The main issue is that Domoticz doesn't provide an authentication mechanism for the websocket interface. That means you must whitelist the source IP address otherwise the websocket interface won't work.

**Comment by JRB202** [comment]
I now use this whitelisting :
127.0.0.*;192.168.*

But WebSockets still fails :
Websocket failed, switch back to http. Check IP whitelisting in Domoticz.

**Comment by JRB202** [comment]
I also just tried to use dashticz bast beta instead of master
Same error with websockets

**Comment by JRB202** [comment]
I just realized that in my CONFIG.js I had an access to domoticz defined via nginx proxy.
I defined direct access to local IP on https port of domoticz in CONFIG.js and fixed the problem.
Now websockets works
Thanks for help
