### ISSUE TITLE
Graph : borderWidth and borderDash Usage

### ISSUE THREAD

**Issue by JRB202** [Dashticz/dashticz#1170]
I already tested the borderWidth and borderDash  properties at line graph object level and saw they are applied for all datasets lines

==> Is there a way to define borderWidth and borderDash  at dataset level in dashticz custom graph ?

It would be very useful to represent 2 qualitative extra data related to each datasets.

**Comment by JRB202** [comment]
Apparently it is possible in graph.js :

datasets: [{
    label: 'My Dataset',
    data: [/* your data here */],
    borderWidth: 2, // Set the border width to 2 pixels
}]

datasets: [{
    label: 'My Dataset',
    data: [/* your data here */],
    borderDash: [5, 10], // Create a dashed line with 5-pixel dashes followed by 10-pixel gaps
}]

How can I do the same in dashticz ?

**Comment by lokonli** [comment]
Implemented in graphtest branch.

The following dataset options can be set:

    * hideData: true  (to hide the dataset completely)
    * hidefromlegend: true (to hide the dataset from the legend only)
    * legend: 'Temp 1' (to set the name of the dataset in the legend)
    * yAxis: 'yaxis' (Name of the y-axis that will be used for this dataset)
    * yLabel: '(m3)'` (to use '(m3)' as label behind the data in the tooltip)
    * backgroundColor: 'red'
    * barPercentage: 0.9
    * borderColor: 'yellow'
    * borderWidth: 3
    * borderDash
    * pointRadius: 4
    * pointStyle
    * pointBackgroundColor: 'blue'
    * pointBorderColor: 'green'
    * pointBorderWidth: 3
    * lineTension: 0.4
    * spanGaps: true
    * fill: 'te_2'
    * stepped: true
    * type: 'line'
    * order: 2
