### ISSUE TITLE
Accessing domoticz device value inside beforeFirstRenderHook() hook

### ISSUE THREAD

**Issue by JRB202** [Dashticz/dashticz#1178]
In order to dynamically build block and graph inside dashticz custom.js  beforeFirstRenderHook()

I need to read the realtime last value of a subtype 'Text' domoticz device using its name or idx
the result to be returned is an alphabetic string and not a number

==> What is the syntax to be used to send this command to domoticz server using domoticz-api.js ?
/json.htm?type=command&param=getdevices&rid=263
Value is available in result.Data

==> Or may I use something like :
var deviceValue = dzVents.devices(Idx).sValue;

But apparently global variable dzVents is not accessible in custom.js  beforeFirstRenderHook() context.

**Comment by lokonli** [comment]
You can use Domoticz.getAllDevices(263).Data

**Comment by JRB202** [comment]
Yes !!!
