### ISSUE TITLE
Public transport tvguide and garbage not loading after crash

### ISSUE THREAD

**Issue by erikhagemeijer** [Dashticz/dashticz#125]
I have Dashticz working ok, but after a crash of the Pi everything is working ok, only the previous configured public transport, tv guide and garbage shows only Loading...
To test I added traffic information, which is working fine.

Is there a temp file that I need to delete, or does anyone have any idea for this problem?

Thanks for a nice dashboard for Domoticz!

**Comment by lokonli** [comment]
Public transport, TV guide and garbage all use the PHP CORS proxy, while traffic information doesn't need a CORS proxy.

So I guess PHP is not enabled on your web server. The installation instructions describe how to enable PHP. You can also try the automatic install script. See:
https://dashticz.readthedocs.io/en/master/gettingstarted/installation.html

**Comment by erikhagemeijer** [comment]
In the Info tab of the configuration settings the installed versions are:
Domoticz version: 4.11474
dzVents version: 2.5.0
Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) 
PHP version: 7.3.11

So I guess PHP is running, but somehow not working.

So I resqued my config file, removed everyting and reinstalled dashticz again.

Thanks for you help.
