### ISSUE TITLE
Use value of some other IDX in custom.js (Feature)

### ISSUE THREAD

**Issue by Ierlandfan** [Dashticz/dashticz#138]
How to get the variables of different idx: 

Why:
Example: I want my CV Block (IDX1) image changed based on the IDX value of IDX2. 
After that the ideas are endless. There must be a smart way.
  
How I now use it is like this but it scews up the probed block:
[code]
var deviceState='';

function getBlock_2(device, idx){ 
$('.block_'+idx);
if (device['Level']= 0) deviceState='Off';
else if (device['Level']= 10) deviceState='CV';
else if (device['Level']= 20) deviceState='WW';
else window.deviceState='Error';
console.log("DeviceState inside function", deviceState); //It works
return deviceState;
}

function getBlock_1(device, idx){
console.log("DeviceState value IDX2 inside another function", deviceState); //It works
}
[/code]

I will make it a feature request

**Comment by lokonli** [comment]
You should use the getChange function. Approximately as follows:
    
    function getStatus_1(idx, value, device) {
	console.log(device.Level)
	if (parseFloat(device.Level) === 0) {
		$('div[data-id="mytitle"] .dt_title').html('level 0')
		$('div[data-id="mytitle"] .col-icon').html('<em class="fas fa-train"/>')

		blocks['373'].title='also 0'
		blocks['373'].icon='fas fa-train'
	} else {
		$('div[data-id="mytitle"] .dt_title').html('level is not 0 but ' + device.Level)
		$('div[data-id="mytitle"] .col-icon').html('<em class="fas fa-bus"/>')

		blocks['373'].title='not 0, but ' + device.Level
		blocks['373'].icon='fas fa-bus'

	}
}


The getChange_1 function gets called when the data of device with index 1 changes.

This example shows how to update a blocktitle defined as blocks['mytitle']
Not only the blocktitle will change, but also device with index 373.

The domoticz blocks gets updated normally every 5 seconds, depending on the config['domoticz_refresh'] parameter. So it might take 5 seconds until block 373 gets updated after the change of device 1.

The exact code depends on the trigger device, and what kind of block you want to change.
