### ISSUE TITLE
Empty black page after Dashticz login 

### ISSUE THREAD

**Issue by failover88** [Dashticz/dashticz#147]
Hello,

I have made a fresh install of Dashticz and followed documentation (https://dashticz.readthedocs.io/en/master/gettingstarted/manualinstall.html) but when I try to access to dashticz, it shows loading but it ends in a empty black page, looking at http://domoticz/dashticz/index.html (I am using a local DNS for where domoticz is hosted)

In configuration I have used default one, but pointed for the current IP with my domoticz custom port,  8080, and set a language:

var config = {}
config['language'] = 'pt_PT';
config['domoticz_ip'] = 'http://127.0.0.1:8080';
config['app_title'] = 'Dashticz V3';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';

I tried with and without language being set.

Do you know what can be?

If you need more info, let me know.

**Comment by lokonli** [comment]
Dashticz runs in your browser. The Domoticz IP must be accessible from the browser.
So I guess 127.0.0.1:8080 is not correct, and should be something like http://domoticz:8080

If the above is not the issue, then check the following:

Have you enabled user authentication in Domoticz?
user authentication in Domoticz must be set to 'Basic Auth' (not login) and you must define the username and password in Dashticz CONFIG.js.

Do you  have defined some Favorites in Domoticz? If not, you have to add the following to CONFIG.js:

config['use_favorites'] = 0

Are you using the beta or the master version of Dashticz?

For debugging:
If you open Dashticz in Chrome and you press F12 then the Developer Window opens. On the console tab you might see errors. On the network tab you might see some failing network request.

**Comment by failover88** [comment]
Damn I totally forgot to use the external IP since it was placed in the same machine of Domoticz. Its working now!

Thanks for the help lokonli!
