### ISSUE TITLE
[enh] Open Domoticz and other local IP addresses via Dashticz proxy.

### ISSUE THREAD

**Issue by lokonli** [Dashticz/dashticz#151]
We could do this via php.

**Comment by dgrostoto** [comment]
Just in case if it can help, see issue https://github.com/Dashticz/dashticz/issues/241
 with a alternative way of going.

**Comment by aalwash** [comment]
There is only one security issue with proxy-ing stuff through PHP
Currently, you really need access to domoticz, before the XHR calls will start working

But if you proxy through PHP, then you only need access to dashticz, doesn't matter from which IP/address
Currently, if someone finds my dashticz URL, he/she can only the parts of the dashboard that don't need domoticz access (like weather blocks)
If you proxy this information, they have full control

So an extra login is required to avoid any unauthorized access

**Comment by lokonli** [comment]
If still relevant please reopen.
