### ISSUE TITLE
Questions regarding buttons parameter "refresh"

### ISSUE THREAD

**Issue by Hoiss** [Dashticz/dashticz#163]
Hi there,

very nice project, I invested days in making my dashboard as perfect as possible and I love it!
Just the documentation is not the very best if you want to realize something like a slideshow frame or if you are looking for some specific details.

In this case here at [https://dashticz.readthedocs.io/en/master/blocks/buttons.html#parameters](url) you can read there's only a "refreshiframe" parameter, but at the examples below (and I found it also in other examples) there's the parameter "refresh".
It would make sense to me that there is a parameter like "refresh", but what's the default for this?
Why is there a limit of 99999ms for "refreshiframe" and is this also valid for "refresh"??? (could it be increased???)
I have some webcams included that I only want to update once per hour, seems that's not possible with the 99999ms restriction, is it?

**Comment by lokonli** [comment]
We are trying to improve the documentation and keeping it up-to-date.
Thanks for your suggestions.

The refreshiframe parameter is used for updating the popup window after pressing the button.
For updating the image of the button itself the 'refresh' or 'refreshimage' parameter can be used.
(they are the same)

The default is 60000 (=1 minute)

In fact there is no maximum to the refresh/refreshimage/refreshiframe parameters, so you can increase it to  3600000 or more.

I'll update the documentation

**Comment by Hoiss** [comment]
Hi,
thanks for your answer, this helps because it's enough for me to know that an increased value does completely work as expected.
Again, great work. I can understand that the documentation is always behind the implementation ;-)

**Comment by lokonli** [comment]
Issues will be closed after updating the documentation.

**Comment by HansieNL** [comment]
Documentation updated

**Comment by Hoiss** [comment]
Do I look at the wrong documentation at https://dashticz.readthedocs.io/en/master/blocks/buttons.html#parameters or why can't I see the changes?

**Comment by lokonli** [comment]
You have to look at the beta version. I'll release a new master soon.
