### ISSUE TITLE
Support for arming/disarming Domoticz security

### ISSUE THREAD

**Issue by dannybloe** [Dashticz/dashticz#165]
Howdee folks, 

Maybe I missed it but it would be nice to have support for arming/disarming Domoticz security panel. So if the system is armed then Dasthicz only shows a code-entry interface to disarm. Thing is, when the panel is in the living room and security is armed, possible intruders should not have access to all devices and switches. 

Cheers, 

Danny

**Comment by lokonli** [comment]
Sounds ok.

The Dashticz beta branch already contains a security panel block, which could be used for this.

A full screen element containing the security panel block could be displayed as long as security state== 'arm away'

**Comment by clinkadink** [comment]
This is now available in the latest beta.
