### ISSUE TITLE
Buttons opening frame: autoclose after configurable time

### ISSUE THREAD

**Issue by Hoiss** [Dashticz/dashticz#174]
Hi again,

this is a feature request to add parameters for buttons that give an option to autoclose the opened frame of it after a configurable time of seconds.
This is e.g. relevant if you want your dashboard to always display a status screen that includes webcams. If you click the webcam an frame gets opened which currently stays opened until any user clicks it away... this should be possible automatically after some time.
I also use buttons to control my roborock vacuum. The button just has to call a php address with parameters and the frame just should give a short info about the returning value and close itself after some seconds. at the moment it stays open until someone closes it.

**Comment by Hoiss** [comment]
I just want to kindly ask if this feature request might have any chance to get included in a future version?
I could imagine a frame autoclose after some time would be useful in any case to ensure an always clean and readable dashboard after some time.

**Comment by lokonli** [comment]
Implemented in 3.7.2.
Check auto_close block parameter
