### ISSUE TITLE
Graph setHeight calc too large

### ISSUE THREAD

**Issue by clinkadink** [Dashticz/dashticz#180]
Hi Lokonli,

I noticed that the calculation for setHeight results in a slightly larger figure than what it should be. This is only noticable when adding multiple graphs to the same screen. 

The calculation is:

`var setHeight = Math.min(Math.round(graphwidth / window.innerWidth * window.innerHeight), window.innerHeight - 50);`

When I have 4 graphs filling one screen, it calculates the height for the first 2 graphs in column 1. Because the height is slightly too large, it automatically shows the scrollbar. This means the window.innerWidth is now smaller (due to the scrollbar), resulting in the 3rd and 4th graph's height to be slightly shorter. The bottom of the lower left graph is off the screen, and sits behind the screen counter (in my case 3 dots, for 3 screens).

Hopefully this makes sense. See below, especially the middle of the screen where you can see the different heights ...

![image](https://user-images.githubusercontent.com/33834551/72220517-526d4900-3549-11ea-92cf-e0b6f295833f.png)

I debugged this in dev tools to see what was actually happening.

![image](https://user-images.githubusercontent.com/33834551/72220290-176a1600-3547-11ea-9da1-342ea3763981.png)

Above shows Graph Width (GW), Graph Height (GH), Window Width (WW) and Window Height (WH). As you can see, the height changes on the 3rd and 4th graph, due to the inner window width being smaller (due to the scrollbar appearing).

I made a minor change to the setHeight calculation with "- 25" from the window.innerHeight:

`var setHeight = Math.min(Math.round(graphwidth / window.innerWidth * window.innerHeight - 25), window.innerHeight - 50);`

![image](https://user-images.githubusercontent.com/33834551/72220469-c0654080-3548-11ea-8297-f004d41af5f0.png)

The updated setHeight calc now reports that all graphs get the same width and height.

![image](https://user-images.githubusercontent.com/33834551/72220559-b2fc8600-3549-11ea-9577-fe8804214142.png)

I have tested this at various resolutions and it works well (3840x2160, 1920x1080, 1600x900, 1366x1024, 1360x768, 800x480).

I have updated the graph.js of my fork of the beta.

Cheers
Chris

**Comment by lokonli** [comment]
Solved in multigraph branch
