### ISSUE TITLE
Buienradar Image not loading

### ISSUE THREAD

**Issue by Earthweb-EWS** [Dashticz/dashticz#200]
Since updating dashticz to 3.3.2, the Buienradar image is not loading anymore.
Rollback to previous release makes it work again.

The image source is 'img/https://api......' and not 'https://api......'

Maybe it is a generic image issue in Dashticz and not Buienradar component?

**Comment by Earthweb-EWS** [comment]
It seems the button parameters are changed. There was no releasenotes, so i compared the two releases.
Change image to btnimage and Buienradar is working again.

**Comment by MHolkamp** [comment]
Where do i have to change image into btnimage?
