### ISSUE TITLE
calendar no longer work

### ISSUE THREAD

**Issue by MSe-5-14** [Dashticz/dashticz#215]
After updating to version 3.3.3 the calendar stopped working. Looks like there is an issue with IcalParser.php. error below

`PHP Parse error:  syntax error, unexpected '=' in /var/www/dashboard/vendor/dashticz/ical/vendor/om/icalparser/src/IcalParser.php on line 131, referer: http://webserver/dashboardv3/`

Dashticz Version 3.3.3
Apache Version 2.4.10 (Debian)
PHP Version 7.0.33-1

**Comment by lokonli** [comment]
Could you try upgrading to PHP 7.1?

**Comment by MSe-5-14** [comment]
I upgraded the php version of my server to 7.4 and this solved the issue. thanks for your help
