### ISSUE TITLE
Improve EvoHome (and thermostat) multiclick behavior

### ISSUE THREAD

**Issue by lokonli** [Dashticz/dashticz#217]
See https://www.domoticz.com/forum/viewtopic.php?p=234417#p234417

**Comment by lokonli** [comment]
Multiclick takes too much time, because you have to wait some time between each click.

This could be solved by updating the value locally in Dashticz after each click, but only send the updated setpoint to Domoticz after some idle time.

**Comment by clinkadink** [comment]
I am working on this.

**Comment by lokonli** [comment]
Solved in beta 3.4.0
