### ISSUE TITLE
Feature request: Sonos capability for Streamplayer

### ISSUE THREAD

**Issue by JLindhout** [Dashticz/dashticz#225]
Hi 

Am using the Sonos API from jishi ( [https://github.com/jishi/node-sonos-http-api](url) ), and was wondering if feasible to integrate into the existing Streamplayer. 

e.g. in the following way

`var _STREAMPLAYER_TRACKS     = [
{"track":1,"name":"Sonos favorite","link": "http://localhost:5005/living room/favorite/[favorite name]"}, 

 {"track":2,"name":"Sonos playlist","link" : "http://localhost:5005/living room/playlist/[playlist name]"},

{"track":3,"name":"Sonos preset","link" : "http://localhost:5005/preset/preset_1"},
];`

By changing "file" to "link" or something, one would have both capabilities. My thinking, but maybe too simplistic. 

Now I have it in a drop-down list, but this would be a more professional solution. 

Jeroen

**Comment by lokonli** [comment]
That is doable. How are your coding skills? ;)

We could also use something similar as the Spotify plugin.

Is it possible to request which Sonos playlists are available via the http api?

**Comment by JLindhout** [comment]
Hi, 

I like the optimism ! :-)
My coding skills are rusty (pascal, FORTRAN, basic, c and now a bit of LUA), but happy to help in anyway. Copy / paste / adapt I can do :-) 

Checked, the API today does not allow to query the favorites or playlists. The presets however are just JSON files in a directory, should be easy to get that into an array. 

Don’t have Spotify, so never looked at the plugin here. 

Jeroen 
PS. Is there a donation possibility for Dashticz, could not find it anywhere. I clever piece of work needs to be rewarded. 

Verstuurd vanaf mijn iPad

**Comment by lokonli** [comment]
You can help, I see :)
Javascript is fun.
Install Visual Studio Code. VS Code supports a remote connection, which is my preferred way of working.

There is some documentation here:
https://dashticz.readthedocs.io/en/master/develop/develop.html

If you start with code, always derive a branch from the beta-branch. See https://dashticz.readthedocs.io/en/master/develop/code.html#github-workflow

I've made a first step in a kind of plugin mechanism for Dashticz. You can use the streamplayer component as an example:
https://github.com/Dashticz/dashticz/blob/master/js/components/streamplayer.js

Information on how to create Dashticz components:
https://dashticz.readthedocs.io/en/master/develop/code.html#design

Enjoy :)

**Comment by JLindhout** [comment]
Thanks for setting me up here, I will give it a go in the coming days!  

Keep you posted.
Jeroen 

--- Sent from mobile device ---

**Comment by lokonli** [comment]
Thanks, perfect!
If you need any help don't hesitate to ask.
If you create an account on slack.com, I'll invite you for the Dashticz channel.

**Comment by JLindhout** [comment]
﻿Hi Sander, account created. 
Is me even niet duidelijk waar dit Bericht nu hen gaat. 

Groet, 
Jeroen

Verstuurd vanaf mijn iPad

**Comment by lokonli** [comment]
What's your username on Slack? I can't find you. Can you contact me on Slack? (@lokonli)

**Comment by lokonli** [comment]
No update for a long time. No action planned. Please create a new issue if still relevant.
