### ISSUE TITLE
Handle local & wan configuration in single config var WITHOUT proxy

### ISSUE THREAD

**Issue by dgrostoto** [Dashticz/dashticz#241]
Hello,
I find that my local configuration is not workable from a remote access. This is due to the front aspect of dashticz. Since this is a kind of bunch of scripts executed on the browser locally (i'm talking only about domoticz access not the CORS proxy for other services), this is the web browser that query directly to domoticz IP:port using json api. But the script do presently not care if the access is possible from current client IP.
In my configuration domoticz IP is a local network IP (192.168.x.x) and my internet access provider is unable (as many other in my country) to loopback public IP adress.
The idea is to make script detect the IP client (could be done in PHP , any CGI script or rather simpler using apache with mod_header with REMOTE_ADDR variable) and depending if a private IP or public IP  is used for the user agent(client) use the corresponding IP that would be specified in js config variable, such as :
config['domoticz_private_ip'] = 'http://192.168.1.3:8084';
config['domoticz_public_ip'] = 'http://80.10.54.42:8080';
so dashticz could be used transparently from local or remote access.
(NB : actual 'domoticz_ip' should be kept as is for compatibility)

Can it be done ?

**Comment by dgrostoto** [comment]
could also be applied to 'refresh' config parameter, in order to match network performance.

**Comment by aalwash** [comment]
I've the same issue, so for now I've fixed it like this:
```
if(window.location.href.indexOf('domoticz.myprivatedomain.nl') > -1) {
        config['domoticz_ip'] = 'http://dns.to.my.domoticz.public.ip.myprivatedomain.nl:8080';
}
else {
        config['domoticz_ip'] = 'http://192.168.0.108:8080';
}
```

So basically, I check the current URL In the browser and based on this I change the domoticz_ip
Of course this can used for IP's as wel:
`if(window.location.href.indexOf('80.10.54.42') > -1)`

**Comment by dgrostoto** [comment]
Thanks for the idea : 
This way of doing is interesting, does this (window.location.href) work in a webview ?

**Comment by aalwash** [comment]
Not sure to be honest, if it's a "inline" simplified browser, then probably it is

**Comment by dgrostoto** [comment]
Tried your proposition but i am now facing a CORS error. I don't understand this error since both dashticz and domoticz server have the "Access-Control-Allow-Origin: *" header in response headers. Do you have any ideas ? (PS : the domoticz is https with the domoticz certificate delivered in the package, but the dashticz server is http only, and of course domoticz and dashticz are on different tcp port).

**Comment by dgrostoto** [comment]
OK i succeed. My problem was due to domoticz asking a user/pass in non local configuration and i forgot to add user_name and pass_word in the if (ip_wan) section. I was messed about the CORS error which is a misinterpretation by the browser of the 401/503 (unauthorized) which was just a simple user/pass error.
Since a alternative way of doing is available, this issue can be closed.
Thanks aalwash

**Comment by dgrostoto** [comment]
Since a alternative way of doing is available, this issue can be closed.
