### ISSUE TITLE
[enh] All blocks: possibility to use of icons/images for all blocks

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#26]
Now there a blocks where adding an image is not possible, because of it's fixed code.
For example: `publictransport.ovinfotrains= { image: 'ns.png', station:...` The image will not be shown.

**Comment by aalwash** [comment]
Isn't this the same issues as #14 ?

**Comment by lokonli** [comment]
I've fixed and closed it for blocktitles, see #14.
I'll use the fix as a template for the other blocks as well.

streamplayer
publictransport

more?

**Comment by HansieNL** [comment]
I'll try to complete my list...
- traffic
- train
- news
- gas
- energy
- thermostat setpoint

**Comment by lokonli** [comment]
streamplayer
publictransport
traffic
train
news
gas
energy
thermostat setpoint
longfonds

This is becoming to much to make a fix 10 times. I'm going to switch to a class based block template architecture. Quite a change, so implementation will take more time.

**Comment by HansieNL** [comment]
Take your time. To keep it simple it is better that icons/images can be changed the same way.

**Comment by lokonli** [comment]
Progressing.
Finished the general framework. Updated streamplayer, frame and news.
After I've finalized the other 'special' blocks (publictransport, traffic, longfonds) I'll merge it into beta.

**Comment by lokonli** [comment]
Progressing.
See #94 
https://github.com/Dashticz/dashticz/tree/toComponents
https://dashticz.readthedocs.io/en/tocomponents/releasenotes/upgrading/v320.html

**Comment by lokonli** [comment]
Solved in v3.2.0 beta.

See #108

**Comment by abaratian** [comment]
no, still the image/icon for thermostat cannot be changed
