### ISSUE TITLE
cannot display camera anymore

### ISSUE THREAD

**Issue by zerr0s** [Dashticz/dashticz#269]
Hi, forgive me for my bad english.

I have upgraded to 3.3.3 and I have an issue to display my camera. It seems that the URL is false:

```
buttons.webcam = {
  width: 12,
  isimage: true,
  refresh: 1000,
  image: 'http://mycam.zerr0s.net:8081/snapshot.cgi?user=xxxx&pwd=xxxx'
};
```

`Request URL: http://domos2.zerr0s.net/dashticz/img/http://mycam.zerr0s.net:8081/snapshot.cgi?user=xxxx&pwd=xxxx`

http://domos2.zerr0s.net/dashticz is the base URL to access dashticz in my LAN.

Any solution to fix this ? Thanks

**Comment by lokonli** [comment]
You have to change 'image: ...' to 'btnimage: ...'
See:
https://dashticz.readthedocs.io/en/master/releasenotes/upgrading/v320.html

**Comment by zerr0s** [comment]
juste finished to deploy with the correct label. nice !!! Thanks!
