### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by geertvercamer** [Dashticz/dashticz#321]
Any chance for an update?
Thanks

**Comment by lokonli** [comment]
What is your question? A specific update in mind?

**Comment by geertvercamer** [comment]
It is always useful to know what is new or has changed with a new release.

If ie. only a new garbage system has been added, I could easily skip that
release

Mvg,

Geert

**Comment by lokonli** [comment]
Something like this:?

https://dashticz.readthedocs.io/en/beta/releasenotes/index.html

**Comment by geertvercamer** [comment]
I am an idiot. I don't know why I haven't seen this, I checked the page
multiple times.
Sorry about this.


Mvg,

Geert

**Comment by geertvercamer** [comment]
Maybe I'm not bad: for some reason the recent updates don't always appear
in the release notes:
[image: image.png]

Met vriendelijke groet,


Geert

**Comment by lokonli** [comment]
I can't see the image you posted.
Be aware there are several documentation trees.
Master:
https://dashticz.readthedocs.io/en/master/

Beta:
https://dashticz.readthedocs.io/en/beta/

The recent changes are only visible in the beta tree.
