### ISSUE TITLE
[bug] Open Weather Map Station Code does not work

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#35]
[https://www.domoticz.com/forum/viewtopic.php?f=67&t=29081#p222151](https://www.domoticz.com/forum/viewtopic.php?f=67&t=29081#p222151)
config['owm_city'] = 'Rijswijk'; works
config['owm_city'] = '2748075'; not
Maybe it's possible to add an additional config option ``config['owm_city_id']``

**Comment by lokonli** [comment]
Fixed and merged in beta.
