### ISSUE TITLE
refresh seems to be a only true or false

### ISSUE THREAD

**Issue by Znubbis** [Dashticz/dashticz#356]
I cant get refresh or refreshimage to work, if i have anything higher than 0 it will update once a second or faster if i set forcerefresh to 2. My raspberry Pi gets bogged down with all the updates and its also unnecessary  load on the network and cam.

Any idea what i have done wrong or is this a bug?

buttons.webcam = {
	width:12, 
	isimage:true, 
	forcerefresh: 1,
	refresh:5,
	btnimage: 'http://192.168.102.46/snap.jpeg'
}

**Comment by lokonli** [comment]
Are you using master? Then refresh still is in msec.

**Comment by Znubbis** [comment]
Thank you that works!
