### ISSUE TITLE
no graph for some dummy devices?

### ISSUE THREAD

**Issue by michapr** [Dashticz/dashticz#404]
Hi,
thanks for the dashboard, just testing ;)

I cannot see any graph for my dummy devices like voltage and distance - the element will not be highlighted - so nothing happen on a click.

Second question - for sensors (door/window) and switches - can there be enabled a graph/log?

Thanks!
Michael

**Comment by lokonli** [comment]
What are the device types and subtypes for 'voltage' and 'distance'?
You can request them from domoticz by browsing to:
http://<domoticz-ip:port/json.htm?type=devices&rid=IDX

replace IDX with the Domoticz device idx.

As temporary workaround you can add 'graph:true' to your block definition. This enables the click behavior. However, we might have to configure the graph data as well. Please let me know whether it works.

**Comment by lokonli** [comment]
It will not work for on/off sensors and devices btw. Maybe something for future developments.

**Comment by michapr** [comment]
> What are the device types and subtypes for 'voltage' and 'distance'?
You can request them from domoticz by browsing to:
http://<domoticz-ip:port/json.htm?type=devices&rid=IDX

1) HardwareType: Dummy, Type: General, Subtype: "Distance"
2) HardwareType: Dummy, Type: General, Subtype: "Voltage"

Thanks,
Michael

**Comment by lokonli** [comment]
Graphs for Voltage and Distance enabled in latest beta.
#406
