### ISSUE TITLE
Feature request: Start fullscreen

### ISSUE THREAD

**Issue by Tsjippy** [Dashticz/dashticz#421]
I would like to have a setting so that whenever Dashticz loads, it loads in full screen, i.e. running the js function toggleFullScreen(element).

maybe with a parameter like this: `config['fullscreen'] = true;`

Even beter would be if it was callable from url:  `domoticzip:8082/fullscreen`

**Comment by lokonli** [comment]
Most browsers don't allow to switch to full screen without user interaction.
If you want to have a full screen Dashticz, I can recommend Fully Kiosk Browser on Android.

**Comment by Tsjippy** [comment]
ah ok, didn't know that.

I dont want to use a kioskbrowser, I want to start it full screen, but it must be easy to exit the fullscreen.
As I work around I use selenium and python on my rpi: `driver.find_element_by_xpath('//*[@id="fullScreenToggleIcon"]').click()`

**Comment by lokonli** [comment]
ok. I'll close this issue

**Comment by Tsjippy** [comment]
But I have found another problem: On a dashticz refresh the fullscreen is also turned off

**Comment by DaeMonSx** [comment]
> But I have found another problem: On a dashticz refresh the fullscreen is also turned off

Yes, I have found the same issue. Any solutions, fix?
