### ISSUE TITLE
Feature request: Setting the default graph for one graph

### ISSUE THREAD

**Issue by Tsjippy** [Dashticz/dashticz#422]
It is possible to set the default graph with `config['standard_graph'] = 'day';` It would be awesome if this was also possible for individual graphs: `standard_graph: 'month'`

**Comment by lokonli** [comment]
We'll look into this.

As a workaround you could create a custom graph. See:
https://dashticz.readthedocs.io/en/master/blocks/graphs.html#custom-graphs

The first element of the custom graph will be displayed at start.

**Comment by Tsjippy** [comment]
ok, thanks

**Comment by lokonli** [comment]
This should work in 3.4.7 beta.

range: 'last' (or 'day' or 'month') for standard graphs
or range: 'my custom key' for a graph with custom data.

Can you test?

**Comment by Tsjippy** [comment]
thanks, works!
