### ISSUE TITLE
Strange behaviour with calendar

### ISSUE THREAD

**Issue by slallemand** [Dashticz/dashticz#449]
Hello,

Using dashticz 3.3.3.1 (master branch) I have an issue with calendars.
In fact, some recurring events are not displayed at all in dashticz while some are.

After trying to understand, I guess I have find something : if the recurring event starts in 2016, the event is not displayed but if the event starts in 2017 it's ok.

Attached are the 2 ICS files I use for the test (the events were created on a nextcloud instance)

[Nextcloud-2AH1UN82SG8WRW8TKKW24Q.txt](https://github.com/Dashticz/dashticz/files/4595986/Nextcloud-2AH1UN82SG8WRW8TKKW24Q.txt)
[Nextcloud-PHY4WWJTWR5NQLCIXFH0E.txt](https://github.com/Dashticz/dashticz/files/4595987/Nextcloud-PHY4WWJTWR5NQLCIXFH0E.txt)

Thanks in advance

**Comment by lokonli** [comment]
Which PHP version is reported by Dashticz? (settings icon upper right-> Info tab)

Dashticz makes use of 2 different ical modules. The second ical module requires PHP 7.1 or higher, but handles recurring events in a better way.

**Comment by slallemand** [comment]
I'm using dashticz in docker using php:apache as baseimage (see screenshot for details)

![Capture du 2020-05-08 15-17-24](https://user-images.githubusercontent.com/2827759/81409362-441deb00-913f-11ea-9831-feb53bf83f4b.png)

**Comment by lokonli** [comment]
ok, thanks. I'll try to reproduce and look for a solution.

**Comment by lokonli** [comment]
Apparently the icalparser module limited recurring events until 3 years after creation,
I've changed this to 3 years after now.
Could you test latest beta?

**Comment by slallemand** [comment]
Did a quick test but it seems my dashboard is broken with the beta version.
Will retry as soon as I can.

Thanks for the quick fix !

**Comment by slallemand** [comment]
Hi @lokonli 
Just try with the beta version and a simple dashboard and it works !

Thanks
