### ISSUE TITLE
dashticz doesn't open anymore

### ISSUE THREAD

**Issue by JanvdW304** [Dashticz/dashticz#456]
This afternoon I have updated my RPI4 and updated Dashticz to beta version 3.4.6.

This evening I tried to open Dashticz, which showed (in Edge) the message 'Dashticz v3 is loading...', but that's all. F5 results in a message that the page can't be found. In Chrome the message 'This site can’t be reached <ip address> refused to connect.'

Domoticz runs without problems.

I tried both 'Basic-Auth'  and 'Login page' as authentication methods in Domoticz. Then I did a fresh install of Dashticz and only changes user and password. Unfortunately the result doesn't change. Do I overlook something?

**Comment by lokonli** [comment]
Can you try to whitelist the Dashticz IP adres in Domoticz?

**Comment by JanvdW304** [comment]
How? You mean with local networks? The whole local network is mentioned there (192.168.178.*)

**Comment by Minglarn** [comment]
Well, this is strange.. 
All of sudden my Dash wont open eighter... 
Works on my Note 10 (Android) but not in Chrome (PC)
![image](https://user-images.githubusercontent.com/58695742/81859677-e2f27f00-9565-11ea-8934-efcc1a146a4b.png)

**Comment by lokonli** [comment]
I mean the IP of the browser you use for Dashticz. If the whole subnet is mentioned then that should be sufficient. Your browser also uses a local IP?

**Comment by JanvdW304** [comment]
yes, that's a local IP address as well.

**Comment by Minglarn** [comment]
Nevermind... My ABD (AdblockPlus) in Chrome just thinks my Domoticz page is spam... Solved.

**Comment by JanvdW304** [comment]
I have installed a fresh Dashticz a few times and noticed that at the end of the installation Putty is closed. It's too quick to see if any message is displayed. I can open putty without any problem and a git pull shows the message 'Already up to date.', zo installation seems to be completed.

**Comment by JanvdW304** [comment]
I have installed Dashticz_v2 to check if the problem was caused by the Dashticz update, but got the same problems. So I decided to restore my last night image backup and everything works fine again. Also the pi upgrades and Dashticz upgrade went well. Apparently something went wrong, but I don't know what. Problem solved
