### ISSUE TITLE
No graph shown in IE11 after v3.4.6 Beta update

### ISSUE THREAD

**Issue by josemi73** [Dashticz/dashticz#469]
[EDIT] I have just upgraded to v3.4.7 Beta and the same behaviour. Graph are black.

After upgrading to v3.4.6 Beta, graphs are not shown. I am using dashticz in a arm tablet running Windows 8.1 with Internet Explorer (there is no other browser supported). Will dashticz be supported or must I downgrade to v.3.4.5?

Thank you in advance.

**Comment by clinkadink** [comment]
Not sure what device you have. If has a keyboard, press F12 and check for any errors in the console.

I take it no changes have been made to CONFIG.js or CUSTOM.js before upgrading to the latest beta?

**Comment by josemi73** [comment]
Hi ck
No, I did no changes to CONFIG or CUSTOM after upgrading.
There are errors in console (F12), I try to translate into English:
_"jQuery.Deferred exception: Object.keys: argument is not an object TypeError: argument is not an object"_

![jquery](https://user-images.githubusercontent.com/52371223/82284604-b1304c80-9999-11ea-880a-3c6b19bdc36b.jpg)

**Comment by josemi73** [comment]
If I go to the version 3.4.5, it works fine again. It is failing when version >3.4.5, I suppose because graph changes in the code.
It is Windows 8.1 with ARM and Internet Explorer 11, and there is no chance to use another browser because ARM architecture. Otherwirse, I do understand if there is no worth to fix this issue.
Thank you.

**Comment by lokonli** [comment]
It seems to be the Object.keys() method which is not supported by IE is causing the error.
Fortunately there is a simple 'polyfill':
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys.
I'll make a temporary fix. Please wait a few minutes.

**Comment by aalwash** [comment]
Which IE version are you using @josemi73 
Object.keys() is introduced since IE9, based on the screenshot and the interface this looks more like IE10/11?

**Comment by josemi73** [comment]
@aalwash  IE 11, it is fully updated.

Thank you @aalwash @lokonli

**Comment by aalwash** [comment]
I can reproduce the same error (in IE11) if I update to the latest beta branch
![image](https://user-images.githubusercontent.com/3220347/82321896-e3f83600-99d5-11ea-8a84-cc684458e3f3.png)

**Comment by josemi73** [comment]
I do not know why I was thinking that the problem was related about ARM architecture, great you tested in x86-x64, I guess.

**Comment by lokonli** [comment]
@josemi73 Can you test the ie11 branch?
If it's working I'll merge it into beta.

You know how to switch branches? If not: To switch branch, type the following in a terminal:

    git fetch origin
    git checkout ie11

**Comment by aalwash** [comment]
Works for me @lokonli on that branch, I don't see the IE11 eror anymore

**Comment by josemi73** [comment]
It is working for me too @lokonli , but now I miss dashticz configuration button in the header in IE11 (both ARM and x64). Other browsers (x64) do show config button (Chrome...)
Do you (@aalwash ) see the configuration button?
![dos](https://user-images.githubusercontent.com/52371223/82330700-75ba7000-99e3-11ea-99c5-1bfcac7c5c85.PNG)

**Comment by lokonli** [comment]
I noticed more icons disappeared. (fa-plug for instance) But that's already the case with Dashticz beta as well, so it seems not to be caused by the updates in the ie11 branch. 

Searching further...

**Comment by lokonli** [comment]
The IE11 regression has been introduced by commit 01ca7b7
The main change is a different jquery-ui module

Trying to find out what's causing the regression...

**Comment by lokonli** [comment]
ok, it seems the icon regression was caused by the upgrade of FontAwesome from 5.12.1 to 5.13.0
I've reverted that in the latest ie11 branch.

Could you test?

**Comment by josemi73** [comment]
@lokonli working fine both issues (config button and graphs).
Thank you so much

**Comment by lokonli** [comment]
A specific reason for reopening?

**Comment by josemi73** [comment]
I have just reopened to be informed when ie11 branch is going to be merged to beta, ie11 branch is working properly now.
Regards

**Comment by lokonli** [comment]
Ok, thanks for the feedback. Probably I'll merge this into beta later today.

**Comment by josemi73** [comment]
> A specific reason for reopening?

I had commented the reason of the opening before reading this ;-)

**Comment by lokonli** [comment]
See 3.4.8-beta, #475

**Comment by josemi73** [comment]
Must I do this for switching back?:
git checkout master

anything else?

**Comment by lokonli** [comment]
It has not been merged into master yet: There are few other issues that I want to solve before releasing a new master. You can switch back to beta and pull the latest version:

git checkout beta
git pull

**Comment by josemi73** [comment]
updated to 3.4.8-beta, thank you for your quick fix.
