### ISSUE TITLE
Feature request - Text block clickable

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#481]
Would be great if a text block is clickable so you can open a popup window or new window, just like a button.

**Comment by lokonli** [comment]
Hidden feature.
Define your text block as follows:
```
blocks[18] = {
    icon: 'fas fa-database',
    link:"http://nu.nl",
    //target: "_blank",   //to open the link on a new page
    target: "iframe"      //to open the link in a frame.
}
```

**Comment by HansieNL** [comment]
Great. Now I can show additonal info in a popup iframe.

**Comment by lokonli** [comment]
I'll rename the parameters to the same parameters as for button. The same block parameters as for button will be supported, like:
url (instead of link)
newwindow (instead of target)
forcerefresh
password

Will be updated in next beta.
