### ISSUE TITLE
Data and icon formatting of alert sensor are gone

### ISSUE THREAD

**Issue by JanvdW304** [Dashticz/dashticz#482]
Since I installed version 3.4.9 today I have a problem with the sensor that shows the status of the last backup of my Domoticz database. After my backup is finished a Domoticz script checks the backup integrity and sets a sensor with the value 'date status' (in my case the current value is '25-05 Database OK') and sets the alertlevel to green or red.
![image](https://user-images.githubusercontent.com/59110068/82840151-e07f1600-9ed1-11ea-880f-a5a831c5e487.png)

In Dashticz custom.js I have the following code:
 `function afterGetDevices(){
	if (alldevices[154].Data.includes("Database OK"))
		{ $('.block_154 .fas.fa-database').addClass('warninggreen'); }
	else
		{ $('.block_154 .fas.fa-database').addClass('warningred'); }
	}`

In CONFIG.js a block is defined for this sensor: `blocks[154] = { icon: 'fas fa-database', width: 6, last_update: false }`

Till the upgrade the sensor was presented with a green or red database (depending on db integrity) and the sensor status. Both are gone now: I see a white database and the sensor name instead of the status.
![image](https://user-images.githubusercontent.com/59110068/82840116-c04f5700-9ed1-11ea-8987-d1e1282bbd66.png)

Any idea what changed caused this?

**Comment by lokonli** [comment]
What was your previous version?

**Comment by JanvdW304** [comment]
Good question. I am not sure about the version number, but it was the version of last Saturday (with the decimal fix for the graphs)

**Comment by lokonli** [comment]
My latest update introduced indeed a bug. It explains why the addClass part doesn't work. I'm still searching why the text value is not shown correctly (in your situation).

**Comment by lokonli** [comment]
Could you test latest beta? Should be solved ...

**Comment by JanvdW304** [comment]
Yes, great. It's working again; thanks for you quick response
