### ISSUE TITLE
Camera: Fix issue with adding d=<timestamp> to image

### ISSUE THREAD

**Issue by lokonli** [Dashticz/dashticz#490]
See:
https://www.domoticz.com/forum/viewtopic.php?p=248860#p248853

**Comment by lokonli** [comment]
Can we use the checkForceRefresh function from dashticz.js?
(in combination with the forcerefresh block parameter)

function checkForceRefresh(m_instance, url) {
  //forcerefresh is set to 1 or true:
  //   adds current time to an url as second parameter (for webcams)
  //   adds the timestamp as first parameter if there are no parameters yet
  //forcerefresh:2
  //   calls nocache.php and prevent caching by setting headers in php.
  //forcerefresh:3
  //   adds timestamp parameter to the end of the url

**Comment by clinkadink** [comment]
I have done this now. Will submit a PR soon.

**Comment by clinkadink** [comment]
This has already been resolved.
