### ISSUE TITLE
Garbage Circulusberkel doesn't work

### ISSUE THREAD

**Issue by NilsNijenhuis** [Dashticz/dashticz#537]
**the code beneath doesn't give data back in dashticz v3** 
it does create a empty window see the printscreen.
what am i doing wrong?

//configuring Garbage company
config['garbage_company'] = 'circulusberkel';
config['garbage_zipcode'] = '7423gv';
config['garbage_street'] = 'Dagpauwoog';
config['garbage_housenumber'] = '50';
config['garbage_maxitems'] = '3';
config['garbage_hideicon'] = false;
config['garbage_use_names'] = true;
config['garbage_use_colors'] = true;
config['garbage_icon_use_colors'] = true;

config['garbage'] = {
    gft: {kliko: 'green', code: '#375b23', name: 'GFT'},
    pmd: {kliko: 'orange', code: '#db5518', name: 'Plastic'},
    rest: {kliko: 'grey', code: '#5e5d5c', name: 'Restafval'},
}

![dashboard](https://user-images.githubusercontent.com/68127712/87194132-742d6a00-c2f9-11ea-97e4-55ce7bf94d93.PNG)

**Comment by HansieNL** [comment]
I checked  with 'circulusberkel' and had no problem.
Can you post your problem here [Dashticz - Module - Garbage collector](https://www.domoticz.com/forum/viewtopic.php?f=67&t=17432) so we can try to solve your problem.

**Comment by NilsNijenhuis** [comment]
Oké hansie ik zal hem daar ook even neerzetten.

Mvg nils

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
