### ISSUE TITLE
Garbage: Ophaalkalender.be doesn't work anymore

### ISSUE THREAD

**Issue by lokonli** [Dashticz/dashticz#557]
https://www.domoticz.com/forum/viewtopic.php?f=67&t=17432&p=253817&hilit=ophaalkalender.be#p253817

**Comment by Tankyspanky** [comment]
Yeah they have build a new page with a other url, and its buggy.
Not all onfo displayed it correct according to zipcode and "recyclage park" what they suggest.

**Comment by lokonli** [comment]
ophaalkalender has been replaced by recycleapp
