### ISSUE TITLE
Timeout fetching devices; falls back from websocket to HTML

### ISSUE THREAD

**Issue by jefft4** [Dashticz/dashticz#588]
Dashticz v3.5 master on Ubuntu 20.04; set to use only favourites with approx 50 devices set as favourite in domoticz.  Establishes web socket connection then queries, then times out and falls back.

Domoticz 2020.2 (build 12347) on Ubuntu 20.04; dashticz VM and domoticz machine are on the same physical and logical network and domoticz has the network defined in settings as local / no authentication required.  Neither machine has any firewall.

Looks like it's trying to fetch all devices, rather than filtering for favourites; in that case, it needs a longer timeout as it'll be retrieving ~1,500 records.

Error from the browser (Chrome on Win10):
`Setting up websocket
js/domoticz-api.js:169 [open] Connection established
js/domoticz-api.js:137 Websocket failed, switch back to http. Check IP whitelisting in Domoticz.
js/domoticz-api.js:103 timeout: type=devices&filter=all&used=true&order=Name
(anonymous) @ js/domoticz-api.js:103
bundle.js?t=2:37 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

CONFIG.js top section:
`var config = {}
config['domoticz_ip'] = 'http://domoticz.mydomain.net:8080';
config['standby_after'] = 0;
config['start_page'] = 1;
config['enable_swiper'] = '2';
config['vertical_scroll'] = '2';
config['auto_swipe_back_to'] = 1;
config['auto_swipe_back_after'] = '30';
config['auto_slide_pages'] = 0;
config['slide_effect'] = 'slide';
config['auto_positioning'] = 0;
config['use_favorites'] = 1;
config['edit_mode'] = 1;
config['last_update'] = 0;
config['background_image'] = 'img/bg10.jpg';`

**Comment by jefft4** [comment]
Sometimes, this works, so I guess it's on the edge of the timeout and fails if one of the machines is more busy.  Perhaps make the timeout a config parameter?

**Comment by lokonli** [comment]
I see that use_favorites is indeed not used at the moment. I'll fix that.
As a temporary workaround you can add the devices to a Domoticz plan, and configure Dashticz to use this plan only via the config['room_plan'] parameter. (not documented I noticed ...)

I'll also add a config parameter for the timeout.

**Comment by lokonli** [comment]
The timeout should only appear during the initial request. It's 2 seconds by default, which is relatively long I would say. Maybe check why your Domoticz response is so slow.

I've reenabled the 'use_favorites' settting. I've changed the default setting to 0, meaning all devices will be fetched.

If you still experience time-outs, you can adjust the timeout with the new setting:
config['domoticz_timeout'] = 5000     //5000 msec

I've merged the changes (#589) into most recent beta. Can you test?

**Comment by lokonli** [comment]
I assume this is solved.

**Comment by jefft4** [comment]
Yes, seems okay, thanks!  Sorry I'd not updated the issue; haven't been near dashticz for a couple of weeks because of other work.

**Comment by jefft4** [comment]
I had favourites=1.  With that, it's quick, but it misses some devices that are flagged as favourites and are on the dashboard in the domoticz UI, so I'm not sure its filtering is quite right.
If I set it to take all devices, the initial load (F5 or first opening dashticz) takes approx 20 seconds!!  After that, Chrome's network log shows that it's around 150ms.  I can't work out why there is that huge delay on reloads, but I have identified which step in the process appears to be causing it - see screenshot below of Chrome's network logging.
It's the websocket access from js/domoticz.api.js:169 - it sticks there for around 20 seconds, then displays the dashboard and continues with the later steps, although that step remains 'pending' even after the processing moves on.

Is there something strange happening on the domoticz end of the websocket, perhaps, or is this an issue in the JS code?

![image](https://user-images.githubusercontent.com/14252625/95323759-943bdd80-0896-11eb-8ba7-4d347f324ffa.png)

**Comment by lokonli** [comment]
The websocket connection stays open. That's indicated with the state 'Pending' which is correct.

I noticed that the Domoticz websocket interface doesn't always send updates for all device changes. For that reason there are these additional requests to frequently get an update of all devices via a normal http request (not websocket). Since you have quite some devices, this may explain the 150 ms.

I can't explain why the 'favorites' is not working for all devices. Domoticz filters the devices. Do you receive the devices with 'use_favorites: false' ?

As an alternative method to speed up:
You can add the applicable devices to a room plan in Domoticz, and only request the devices on this room plan in Dashticz via

    config['room_plan'] =  <room plan id>

**Comment by jefft4** [comment]
The devices all show up if favourites is false, yes.  I'm not concerned about the 150ms; what's strange is the 20 seconds at first load looking at the 'Dashticz is loading' spinner - what is it doing at that point?  That's when it times out and drops back to HTTP, if I don't make the timeout very, very long.  My dashboard has only 30 or so blocks defined and half of those aren't in use, but the domoticz system has 100+ devices available to the dashticz user.
There are some strange things going on here, I think... I have temp sensors that show up as blank blocks but if clicked, will chart correctly; setpoints also blank and not clickable.  It would be good to identify what about all these devices is causing dashticz not to work as expected.  Are there any particular attributes of the devices that could cause problems?

**Comment by jefft4** [comment]
Okay, so since I discovered that git was telling me I had the latest beta but in fact it hadn't pulled the js modules properly, and reinstalled, things have improved.
The first load of the dashboard is now about 3 seconds, not 20 seconds.  Much better :-)
Seems your fix worked, just git didn't!  Thanks :-)

Aside - I still have issues with devices that show up as blank blocks; I'm investigating those and I'll raise a new issue if I find any consistent pattern to the problems.
