### ISSUE TITLE
Security devices represented as alarm control, not alarm sensor

### ISSUE THREAD

**Issue by jefft4** [Dashticz/dashticz#612]
I have several door sensors connected via RFXCom, which domoticz treats as device type 'X10 security'.  They show in the domoticz UI with the alarm lamp icon and their valid states are Normal, Alarm and in some, Alarm+Tamper.  However, in dashticz they show up as alarm control devices, with states Armed home, Armed away, Disarmed.

Can this be changed?  I assume that domoticz knows the difference between an alarm sensor and an alarm control button, so it ought to be possible.
![image](https://user-images.githubusercontent.com/14252625/95320776-e29aad80-0891-11eb-9891-db9df802cce6.png)
![image](https://user-images.githubusercontent.com/14252625/95320809-efb79c80-0891-11eb-8bc4-39e7dad3c9a7.png)
![image](https://user-images.githubusercontent.com/14252625/95320845-03630300-0892-11eb-8f50-070b406355fe.png)

**Comment by lokonli** [comment]
Can you post the Domoticz json output of the devices?

http://<domoticz ip:port>/json.htm?type=devices&rid=1570
http://<domoticz ip:port>/json.htm?type=devices&rid=1571

**Comment by jefft4** [comment]
1570:
`{
	"ActTime" : 1602095561,
	"AstrTwilightEnd" : "20:15",
	"AstrTwilightStart" : "05:20",
	"CivTwilightEnd" : "18:57",
	"CivTwilightStart" : "06:38",
	"DayLength" : "11:12",
	"NautTwilightEnd" : "19:36",
	"NautTwilightStart" : "05:59",
	"ServerTime" : "2020-10-07 19:32:41",
	"SunAtSouth" : "12:48",
	"Sunrise" : "07:11",
	"Sunset" : "18:24",
	"app_version" : "2020.2 (build 12453)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 100,
			"CustomImage" : 0,
			"Data" : "Normal",
			"Description" : "",
			"Favorite" : 1,
			"HardwareID" : 38,
			"HardwareName" : "RFXCOM433 USB",
			"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
			"HardwareTypeVal" : 1,
			"HaveDimmer" : false,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "C6F860",
			"LastUpdate" : "2020-09-20 16:20:43",
			"MaxDimLevel" : 0,
			"Name" : "Shed door",
			"Notifications" : "false",
			"PlanID" : "24",
			"PlanIDs" : 
			[
				24,
				14,
				25
			],
			"Protected" : true,
			"ShowNotifications" : true,
			"SignalLevel" : 7,
			"Status" : "Normal",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "X10 security",
			"SwitchType" : "Security",
			"SwitchTypeVal" : 0,
			"Timers" : "false",
			"Type" : "Security",
			"TypeImg" : "security",
			"Unit" : 0,
			"Used" : 1,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1570"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}`

1571:
`{
	"ActTime" : 1602095627,
	"AstrTwilightEnd" : "20:15",
	"AstrTwilightStart" : "05:20",
	"CivTwilightEnd" : "18:57",
	"CivTwilightStart" : "06:38",
	"DayLength" : "11:12",
	"NautTwilightEnd" : "19:36",
	"NautTwilightStart" : "05:59",
	"ServerTime" : "2020-10-07 19:33:47",
	"SunAtSouth" : "12:48",
	"Sunrise" : "07:11",
	"Sunset" : "18:24",
	"app_version" : "2020.2 (build 12453)",
	"result" : 
	[
		{
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 100,
			"CustomImage" : 0,
			"Data" : "Alarm",
			"Description" : "",
			"Favorite" : 1,
			"HardwareID" : 38,
			"HardwareName" : "RFXCOM433 USB",
			"HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
			"HardwareTypeVal" : 1,
			"HaveDimmer" : false,
			"HaveGroupCmd" : false,
			"HaveTimeout" : false,
			"ID" : "70AFA0",
			"LastUpdate" : "2020-10-07 11:35:48",
			"MaxDimLevel" : 0,
			"Name" : "Summerhouse door",
			"Notifications" : "false",
			"PlanID" : "14",
			"PlanIDs" : 
			[
				14,
				25
			],
			"Protected" : true,
			"ShowNotifications" : true,
			"SignalLevel" : "-",
			"Status" : "Alarm",
			"StrParam1" : "",
			"StrParam2" : "",
			"SubType" : "X10 security",
			"SwitchType" : "Security",
			"SwitchTypeVal" : 0,
			"Timers" : "false",
			"Type" : "Security",
			"TypeImg" : "security",
			"Unit" : 0,
			"Used" : 1,
			"XOffset" : "0",
			"YOffset" : "0",
			"idx" : "1571"
		}
	],
	"status" : "OK",
	"title" : "Devices"
}`

**Comment by lokonli** [comment]
Can you test latest beta?
You can set the icons or images via the block parameters
icon, iconOn, iconOff
image, imageOn, imageOff

**Comment by jefft4** [comment]
Already up to date: 8c4806b..775949f  beta       -> origin/beta
I can override the icon (or image, preferably as those are stored locally) but the state buttons remain...  Those simply shouldn't be there; with a sensor, the icon tells us all we need to know.
![image](https://user-images.githubusercontent.com/14252625/95429616-8fccfe80-0942-11eb-800e-e4c6c7e1e269.png)

**Comment by jefft4** [comment]
Also - wrong issue, I know, but could you look at my latest update on #588 ... I don't think we've fully solved the timeouts :-(

**Comment by lokonli** [comment]
hmm, mine looks like attached.
![x10](https://user-images.githubusercontent.com/22852111/95442797-1a6e2780-095c-11eb-91ae-bdbebc8a1823.jpg)

I'll check what's going wrong.

**Comment by lokonli** [comment]
I don't have a real x10 device, but created a stub based on your device info. 
Can you double check that you've the latest Dashticz version?

If yes, I'm afraid you have to help me with debugging ...

In block.js, line 2275, you should see:

    var device = block.device;
      if (block.protected || device.Protected)
        return getProtectedSecurityBlock(block);

(if it looks different, you don't have latest beta ...)

Can you insert one line, like this:

     var device = block.device;
    console.log(block);  //insert this line
      if (block.protected || device.Protected)
        return getProtectedSecurityBlock(block);

If you then open DevTools in Chrome and refresh Dashticz you should see the additional device log in the DevTools console tab.

Can you unfold the object, and also unfold the device object inside of it, and copy/paste the results here?

**Comment by jefft4** [comment]
Strange things...  the code didn't look like that, in spite of git telling me that the version was the latest beta, so I deleted the docker and reinstalled from scratch.  Now it works as you intended; thanks!
![image](https://user-images.githubusercontent.com/14252625/95451296-7dad8900-095f-11eb-8961-3c84351d540f.png)
