### ISSUE TITLE
Blocks show blank or not at all when given friendly names

### ISSUE THREAD

**Issue by jefft4** [Dashticz/dashticz#615]
When I give my blocks a friendly name rather than the idx, some blocks fail to display or display as a blank block.

Example 1, two setpoints:
`// Setpoints
blocks['Hall setpoint'] = {
    title: 'Hall target',
    idx: 1714,
    width:12
}
//blocks['Lounge setpoint'] = {
blocks[1373] = {
    title: 'Lounge target',
    idx: 1373,
    width: 12
}
...
columns[2] = {
    blocks: [1373, 'Hall setpoint'],
    width: 4
`
The lounge setpoint, referenced by idx, displays correctly.  The hall setpoint is a blank, non-clickable block.

Example 2, temperature sensors (these are simple temp-only sensors in domoticz):
`
var blocks={}
// Scenes/groups
blocks['s1'] = {
    title: 'Evening lights',
    width: 4
}
blocks['s15'] = {
    title: 'Morning lights',
    width: 4
}
blocks['s3'] = {
    title: 'Fire alarm reset',
    width: 4
}

// Environmental sensors
blocks['Hall env'] = {
    title: 'Hall env',
    idx: 653,
    width: 12
}
blocks['653_1'] = {
    title: 'Hall',
    width: 12
}
blocks['Landing env'] = {
    title: 'Landing env',
    idx: 507,
    width: 12
}
blocks['507_1'] = {
    title: 'Landing',
    width: 12
}
blocks['Lounge temp'] = {
    title: 'Lounge TRV',
    idx: 1378,
    width: 12
}
blocks['1378_1'] = {
    title: 'Lounge',
    width: 12
}
blocks['Outdoor env'] = {
    title: 'Outdoors',
    idx: 1562,
    width: 12
}
blocks['1562_1'] = {
    title: 'Outdoors',
    width: 12
}
blocks['Vent intake temp'] = {
    title: 'Vent Intake',
    idx: 1687,
    width: 12
}
blocks['Vent supply temp'] = {
    title: 'Vent Supply',
    idx: 1686,
    width: 12
}
// Setpoints
blocks['Hall setpoint'] = {
    title: 'Hall target',
    idx: 1714,
    width:12
}
//blocks['Lounge setpoint'] = {
blocks[1373] = {
    title: 'Lounge target',
    idx: 1373,
    width: 12
}

// Switches
blocks['HW override'] = {
    title: 'Hot water +1hr',
    idx: 430,
    width: 6
}
blocks['CH override'] = {
    title: 'Heating',
    idx: 527,
    width: 6
}
blocks['Vent fan'] = {
    title: 'Vent speed',
    idx: 1706,
    width: 6
}
blocks['Vent fault'] = {
    title: 'VENT FAULT',
    idx: 1533,
    width: 6,
    protected: true
}

// Title blocks
blocks['bt_Temps'] = {
    type: 'blocktitle',
    title: 'Temperature',
    width: 12
}
blocks['bt_Doors'] = {
    type: 'blocktitle',
    title: 'Doors',
    width: 12
}
blocks['bt_HeatVent'] = {
    type: 'blocktitle',
    title: 'Heat & Vent',
    width: 12
}
...
columns[2] = {
    blocks: ['bt_HeatVent', 'Vent fault', 'Vent fan', 'Vent intake temp', 'Vent supply temp', 'Hall setpoint', 1373, 'HW override', 'CH override'],
    width: 4
}
`
These appear as in the image...
![image](https://user-images.githubusercontent.com/14252625/95452888-dbdb6b80-0961-11eb-87cf-54da660d141b.png)

If I change the block and column defs to refer to these by idx - e.g. 1687 rather than 'Vent intake temp' - they display correctly.

**Comment by lokonli** [comment]
Spaces in friendly names currently are not supported. I'll update the documentation. 

Can you try without spaces?

**Comment by jefft4** [comment]
Good without spaces, thanks.  I'm surprised how many devices were working with spaces - all those doors had spaces in their friendly name!

Thanks again :-)
