### ISSUE TITLE
Dial indicators not moving pointer

### ISSUE THREAD

**Issue by bbrowaros** [Dashticz/dashticz#625]
Hi, 

I'm just configuring fresh installed Dashticz and I've notice that the pointer in dial indicator is not actually behaving like the screens on documentation. I've setup following block: 
`blocks ['Temperatura_out'] = {
        idx: [7385],
        type : 'dial',
        title : 'Na zewnatrz',
        setpoint: 15,
        min: -50,
        max: 50,
        shownumbers: true,
        showring: true,
        showunit: true,
        width: 12,
        height: 200
}
`
however the dial display is not moving the indicator (the same is for a thermostat where I can adjust a different value). It is possible that I've missed something but reading the documentation I've got it all set up as examples. Here it  how it looks like: 
![Przechwytywanie](https://user-images.githubusercontent.com/24865361/96355091-2be2cc80-10de-11eb-8ed4-5e567ae01a16.JPG)

I've got the same behaviour on a master (stable) release and beta.

**Comment by lokonli** [comment]
There is an issue with the min/max values. I'll create a fix.

**Comment by lokonli** [comment]
Fixed in latest beta with #629

**Comment by bbrowaros** [comment]
Just pulled the fix and it works without a issue. Thx
