### ISSUE TITLE
not all blocks shown

### ISSUE THREAD

**Issue by rene2716** [Dashticz/dashticz#63]
Hi, 
can you tell me why not all defined blocks are shown, some temperature does show, but for instance my toon devices when created to blocks will no show, any hints ? Tried it in V2 and V3, same behaviour

**Comment by aalwash** [comment]
Can you maybe provide more information?
Do you see any error in the console and maybe share the CONFIG.js?

**Comment by rene2716** [comment]
![image](https://user-images.githubusercontent.com/40685643/65331590-5ef61c00-dbbd-11e9-9096-922211add142.png)

this are the console errors and this is my CONFIG.js, very standard
21,22 and 24 are netatmo devices which look ok, 129 is temp and humid from an esp8266 which shows up allright in domoticz standard dashboard but not in dashticz, tried toon devices also but they don work either. Tried it in 1 column also but that didnt help

var config = {}
config['language'] = 'nl_NL'; //or: en_US, de_DE, fr_FR, hu_HU, it_IT, pt_PT, sv_SV
config['domoticz_ip'] = 'http://xxxxxxxxxxxx:8080';
config['domoticz_refresh'] = '5';
config['dashticz_refresh'] = '60';
config['use_favorites'] = 0; //Request all Domoticz Devices, not only favorites

//Definition of blocks
blocks = {}
blocks[21] = {
  width: 6
}

blocks[24] = {
  width: 6
}
blocks[22] = {
  width: 6
}
blocks[129] = {
  width: 6
}
//Definition of columns
columns = {}
columns[1] = {
 blocks : [129],
  width: 8
}
columns[2] = {
  blocks : [21, 24, 22],
  width: 8
}

//Definition of screens
screens = {}
screens[1] = {
  columns: [1, 2]
}

**Comment by HansieNL** [comment]
If you create your own dashboard you have to add the following setting too:
config['auto_positioning'] = 0;
From the manual:
Configure the ability to define your own positioning for the buttons (in combination with config['use_favorites'])
0 Use this if you have defined your own columns
1 Default

**Comment by rene2716** [comment]
Ha, well that did the trick, strange thing though that it shows some blocks :)
Great software
