### ISSUE TITLE
Pushbutton block

### ISSUE THREAD

**Issue by crispy78** [Dashticz/dashticz#654]
I've got a scene that switches off certain devices and turns on others.
I've created a block:
```
blocks['avondschakeling'] = {
	title: 'Avondschakeling',
	idx: 's5',
	last_update: false,
	speak: 'De avondschakeling wordt ingeschakeld',
	hide_data: true,
}
```
This will prevent showing the status in text, but it will still change the color of the icon and I have to press the button again to "reset" the status of the button. Is there a way to create a pushbutton or could a pushbutton be implemented?

**Comment by lokonli** [comment]
What is your Dashticz version?
I think this was fixed in the beginning of October with #621 
Can you try latest beta?

**Comment by crispy78** [comment]
Hi there @lokonli I’m on the latest master, going to try the latest beta.

**Comment by lokonli** [comment]
If you still encounter issues you can reopen this one.
