### ISSUE TITLE
Issuing issues

### ISSUE THREAD

**Issue by crispy78** [Dashticz/dashticz#657]
I’m a new user of Dashticz and I would like to give some feedback on the way people issue issues at this hub. I see people opening issues, give it a name and put in an URL of the Domoticz-forum or (like) me provide little to no details on the version and circumstances of an issue. Someone has to follow a link or dig into the issue before they can start working on a fix or start developing.
The hub of Tasmota has some rules in place to “prevent” this and most information is on their hub. https://github.com/arendst/Tasmota You have to fill in a form that provides the information to the developers, users can lookup issues (and fixes) all from within that hub.

Keep up the great work on this project.

**Comment by lokonli** [comment]
In fact I'm the only one who is fixing issues at the moment. Currently I use github to track reported issues.

If you are willing to contribute as well that would be great!

**Comment by crispy78** [comment]
About my contributing skills: I'm a jack of all trades, master of none. My programming skills are limited, I can read some code, can write a "Hello world"-script and that's about it :-)

As for the issues, even if you're the only developer I can recommend you to get more details about issues from the issuer. It'll help you in the future. I've seen firsthand that people are still trying to get fixes for Windows XP-machines, just because they're to stubborn to upgrade. Getting as a versionnumber at least will save you time trying to search for a fix that has already been fixed or fix some feature that was abanonned ages ago.

I've been using Domoticz for a couple of years now, still I'm doubting if Home Assistant isn't more suitable for my needs. Dashticz is a truly great addition to Domoticz and I applaud your work. It's easy to setup and works really nice. This platform has great potential.

**Comment by lokonli** [comment]
Thanks for your feedback.

I'll take your advice into account.
