### ISSUE TITLE
RSS feeds maxitems

### ISSUE THREAD

**Issue by tarmacalastair** [Dashticz/dashticz#66]
Hi, fantastic dashboard, many thanks.

Just wondering, might it be possible to have a maxitems (like for the calendars) for RSS news feeds? Some of my feeds that I've added have only a couple of new stories every few days and my feed is now showing stories going back 2 weeks. It would be good to be able to rotate some feeds after a couple of items and other feeds after a much greater number.

Apologies if this is already possible and I've missed something.

Thanks for

**Comment by lokonli** [comment]
Added to latest beta. See #282 

Example:

blocks['my_news'] {
  feed: 'http://www.nu.nl/rss/Algemeen',
  filter : '5 items',  // to only show the 5 latest news items, or:
  filter: '2 days',    // to only show news items of the last 2 days, or:
  filter: '1 month',   // to only show news items from last month
}
