### ISSUE TITLE
Option for special blocks to have "off status"

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#671]
It would be great to have some kind of "off status" for the following special blocks:
trafficinfo: Geen verkeersinformatie
alarmmeldingen: Geen Actuele Meldingen.....
traffic: 0 files, 0 km, 0 meldingen
train:

**Comment by lokonli** [comment]
I've called the css class 'empty'.

The css class 'empty' will be added to special blocks.

You can select non empty blocks via the CSS pseudo-selector:

    .dt_block:not(.empty) {
      /*your styling here */
    }

**Comment by lokonli** [comment]
Implemented after 3.8.9, PR #905
