### ISSUE TITLE
Protected-attribute on blocks not working as expected

### ISSUE THREAD

**Issue by RasmusWesterlundh** [Dashticz/dashticz#75]
The protected-attribute does not work.
 If I set ['protected']=true; for one block, it will either have no effect on that block or it will affect all of my blocks.

Using the below blocks-config:
```
blocks[12] = {
	width: 3,
	protected: true
};

blocks[26] = {
	width: 3,
	protected: false
};
```

After clearing browser cache and reloading Dashticz I am able to switch either all blocks (including block[12]) or I am unable to to switch any block (including block[26]).

Browser console reports 401 Not Authorized on all attempts to toggle switch when it's not working:

> plugins.js:28 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ plugins.js:28
(anonymous) @ plugins.js:49
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js:4
ajax @ jquery.min.js:4
loadFiles @ main.js?v=1570310424524:45
(anonymous) @ (index):73
f @ head.js:6
(anonymous) @ head.js:6
(anonymous) @ head.js:6
o @ head.js:6
load (async)
rt @ head.js:6
b @ head.js:6
(anonymous) @ head.js:6
u @ head.js:6
lt @ head.js:6
(anonymous) @ (index):65
jquery.min.js:4 GET http://192.168.1.11:8080/json.htm?username=[removed]&password=[removed]&type=command&param=switchlight&idx=26&switchcmd=Set%20Level&level=32&jsoncallback=jQuery22408475636819673551_1570310424581&_=1570310424585 net::ERR_ABORTED 401 (Unauthorized)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
sliderSetValue @ VM2854:176
slideDeviceExt @ VM2854:203
start @ main.js?v=1570310424524:2293
_trigger @ jquery.min.js:11
_start @ jquery.min.js:17
(anonymous) @ jquery.min.js:11
_mouseCapture @ jquery.min.js:17
(anonymous) @ jquery.min.js:11
_mouseDown @ jquery.min.js:14
(anonymous) @ jquery.min.js:11
(anonymous) @ jquery.min.js:14
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
jquery.min.js:4 GET http://192.168.1.11:8080/json.htm?username=[removed]&password=[removed]&type=command&param=switchlight&idx=26&switchcmd=Set%20Level&level=18&jsoncallback=jQuery22408475636819673551_1570310424581&_=1570310424586 net::ERR_ABORTED 401 (Unauthorized)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
sliderSetValue @ VM2854:176
slideDeviceExt @ VM2854:208
change @ main.js?v=1570310424524:2299
_trigger @ jquery.min.js:11
_change @ jquery.min.js:17
(anonymous) @ jquery.min.js:11
_mouseStop @ jquery.min.js:17
(anonymous) @ jquery.min.js:11
_mouseUp @ jquery.min.js:14
(anonymous) @ jquery.min.js:11
n._mouseCapture._mouseDistanceMet._mouseDelayMet._mouseUpDelegate @ jquery.min.js:14
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

**Comment by RasmusWesterlundh** [comment]
After some more testing I found that when all requests succeed it is because I am logged on to Domoticz in a different browser tab. And when all requests fail (due not 401 not authorized) it's because I'm not logged in to Domoticz in a different tab.
The same requests succeeds when sent from Postman, regardless if I'm logged on to domoticz or not in the browser.

So I seem to have two issues here:
1. "protected"-attribute on blocks does not work (does not do anything)
2. Setting switch values from Dashticz only works when logged on to Domoticz via the browser

Browser: Chrome Version 77.0.3865.90
Dashticz: v3.0.6 master
Domoticz: v4.11349

**Comment by lokonli** [comment]
Thanks for the analysis! I'll check

**Comment by lokonli** [comment]
I've tested the 'protected' parameter. I don't see issues.

I'll check the authorization as well.

**Comment by lokonli** [comment]
Which authorization method do you use in Domoticz?
Can you try with Basic Auth (via Domoticz -> Settings -> settings-> website protection
The username/password you use in Dashticz must be the same as the username/password you use for Domoticz.

**Comment by RasmusWesterlundh** [comment]
The authorization I use is "website" and not basic auth.
I can copy the same URL that fails from Dashticz ("401 Not Authorized") directly into Postman and it succeeds.
Since it works from Dashticz when I'm logged into Domoticz and stops working when I log off from Domoticz, but always works from Postman, I suspect the issue is with some shared session information in the browser somehow? Seems strange though.
However, I've worked around the issue by adding my Dashticz-clients IP to the "LOCAL NETWORKS (NO USERNAME/PASSWORD):"-setting in Domoticz.


Regarding the protected-attribute I still cannot get it to work. Here's a short GIF-demo of my setup: https://puu.sh/EqHQg/c9e5d206e0.gif

**Comment by lokonli** [comment]
For the login: Dashticz sets the cookie CrewCentreSession=Valid' after successful login, but I don't know how it relates to the issues you have.
If your workaround by the using the "LOCAL NETWORKS (NO USERNAME/PASSWORD):"-setting in Domoticz is acceptable then I'll not further dig into it.

On the protected attribute: Indeed, for dimmers they are not recognized. (only for 'normal' switches). I'll make the fix.

**Comment by lokonli** [comment]
Dimmer protection should work now with the latest beta.
