### ISSUE TITLE
Calendar: layout for only all day events calender

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#779]
If you have an all day calender (for example a birthday calender) and you don't want the time table data cell you have to do that by add code to config.css.
Another layout option without the time table data cell would be great.
[https://www.domoticz.com/forum/viewtopic.php?p=267708#p267708](https://www.domoticz.com/forum/viewtopic.php?p=267708#p267708)

**Comment by lokonli** [comment]
That means that for all items in that agenda there should be no time info? 
That means it will just become:

1-2-2021    HansieNL birthday
3-3-2021    Lokonli birthday

So, also no 'full day' message. 

ok?
