### ISSUE TITLE
Barometer device no popup graph

### ISSUE THREAD

**Issue by 2bbe** [Dashticz/dashticz#78]
Hi
My barometer device doesn't display a pop-up graph when I click on it. 
screenshots:
![bild](https://user-images.githubusercontent.com/40929798/66335102-96ddbd00-e93a-11e9-9985-384863bc6e9c.png)

Comparing the barometer block(333) with a temperature block(10) in chrome's developer tool gives following:
`<div data-id="333" class="mh transbg block_333 col-xs-4">`

`<div data-id="10" class="mh transbg block_10 col-xs-4 hover" onclick="showPopupGraph('10','10');">`

In blocks.js we are missing to check for `device['SubType'] == 'Barometer'` and probably in other places too. I don't have the needed skills to dig further and fix it without risking to break something with combined device types.

Cheers Tobias

**Comment by lokonli** [comment]
Yes, I noticed more devices don't have a graph popup. I'll look how to fix it.

**Comment by lokonli** [comment]
Fix merged in latest beta.
