### ISSUE TITLE
Dashticz doesn't load blocks without internet

### ISSUE THREAD

**Issue by gohamstergo** [Dashticz/dashticz#84]
Heyo,

Could you possibly make Dashticz load when internet is down or unavailable? Currently, without internet, it just loads to a black/blank screen after it says "Dashticz v3 is loading." I've tested on multiple browsers and devices. I assume things like icons require could require internet for fontawesome or some such, but it would be great if the blocks would load anyway and still function with a lan connection to Domoticz.

Thanks for looking into it!
v3.1.0

**Comment by lokonli** [comment]
Can you try to find out which network request prevents Dashticz to start?
In Chrome, press F12, the open Dashticz. In the network tab of the developer window you should see all network requests, and also the one that fails.

**Comment by gohamstergo** [comment]
Looks like it could be the version check. It's the only thing I see that didn't load when testing via chrome on pc.

![loadfail](https://user-images.githubusercontent.com/8529475/66876383-2efd2700-ef77-11e9-9f51-779abbf015b9.jpg)

**Comment by lokonli** [comment]
Fixed in latest beta. Can you test?

**Comment by gohamstergo** [comment]
Mostly same issue on 311. Now, Blocks will load 1 out of every ~10 times after sitting on black for 20 seconds or so.

**Comment by lokonli** [comment]
Can you add the following to CONFIG.js and test:

`config['disable_update_check'] = 1`

**Comment by gohamstergo** [comment]
with update checking disabled, it does load normally. Is this fixable, or will I just need to leave update checking disabled?

**Comment by lokonli** [comment]
Good!
For the time being please use this setting. 

In the future maybe I'll make the loading more robust, but it's not high on my priority list.
I'll make the time out of the version check a bit shorter. Maybe that's sufficient already.
