### ISSUE TITLE
[SOLVED] Update domoticz with v2021.1 and Dashticz doesn't work

### ISSUE THREAD

**Issue by diazovitch** [Dashticz/dashticz#851]
Hi,

I  update domoticz with the version 2021.1 and my dashticz doesn't work.
I think that the database of domoticz has changed.

**Comment by lokonli** [comment]
I didn't dare to update my domoticz yet, but I'll test.

**Comment by lokonli** [comment]
I've updated to 2021.1 Everything seems to work ok.

**Comment by diazovitch** [comment]
I had the dashticz v3.7 master.
I upgrade to 3.8
I will try tomorrow with this upgrade.

**Comment by diazovitch** [comment]
You were right.
This is the whitelist in the domoticz settings.
The update always changes me a ";" in "," which prevents access.
Thank you for your help.
