### ISSUE TITLE
function afterGetDevices() not working

### ISSUE THREAD

**Issue by Doudy** [Dashticz/dashticz#858]
I use Dashticz V3.8.3 beta

I test the function afterGetDevices()
If the idx "78" is "Off", my "rain-1h" block would have to change color.
But nothing works
No reaction !
Do we have to activate the function somewhere?
See my topic : [https://www.domoticz.com/forum/viewtopic.php?f=67&t=36558](url)

> Topic : <
My custom.js
```
function afterGetDevices(){
    if (Domoticz.getAllDevices()[78].Data == 'Off') {
            $('.pluie-1h .title').addClass('warningblue');
            $('.pluie-1h .state').addClass('warningblue');
    }
    else {
            $('.pluie-1h .title').removeClass('warningblue');
            $('.pluie-1h .state').removeClass('warningblue');
    }
}
```
My custom.css
```
.warningred {
  color: red !important;
}
.warningorange {
  color: orange !important;
}
.warninggreen {
  color: green !important;
}
.warningblue {
  color: blue !important;
}
```
My Block
```
blocks['pluie-1h'] = { 
	idx: 84,
	width: 2,
	title: '1h',
}
```
But no result on display

Domoticz device [78]
![image](https://user-images.githubusercontent.com/28684288/124081615-0fa87500-da4c-11eb-94f4-e11aff1632d7.png)

**Comment by HansieNL** [comment]
You have to add '.block_' to the CSS class selector, so like this:
`function afterGetDevices(){
    if (Domoticz.getAllDevices()[78].Data == 'Off') {
            $('.block_pluie-1h .title').addClass('warningblue');
            $('.block_pluie-1h .state').addClass('warningblue');
    }
    else {
            $('.block_pluie-1h .title').removeClass('warningblue');
            $('.block_pluie-1h .state').removeClass('warningblue');
    }
} `

**Comment by Doudy** [comment]
👍
