### ISSUE TITLE
Crash at install

### ISSUE THREAD

**Issue by darrepac** [Dashticz/dashticz#868]
Hi

I tried 4 times and got the same result.
Platform: Rasperry Pi 3 with up to date OS
I follow the automatic install (so Beta), with `. <(wget -qO - https://raw.githubusercontent.com/Dashticz/dashticz/beta/scripts/dashticz_install.sh )`
It never reach the end of the download, it crashes my SSH terminal before (tried 4 times).
I end up logging the SSH (using Putty) and the last lines before crashing are:
```
Réception d'objets:  29% (623/2143), 17.47 MiB | 23.00 KiB/s   
fatal: L'hôte distant a fermé la connexion de manière inattendue
fatal: fin de fichier prématurée
fatal: échec de index-pack
Error. Something went wrong. Exiting
```
I will translate to english:
```
fatal: distant host closed the connection unexpectedly
fatal: premature end of file
fatal: Index-pack failure
Error. Something went wrong. Exiting

```
My internet connection was quite busy but it is the first time I got this.

**Comment by edwin123456** [comment]
I have the same problem 
And i use pi4

**Comment by lokonli** [comment]
It seems Docker install isn't working. What you can do as temporary workaround, is to first manually install docker, and then restart the automatic install of Dashticz. I'll try to fix the docker install in the mean time.

**Comment by lokonli** [comment]
You both probably have a somewhat older Raspbian version. The Docker install script was not able to update/upgrade your system.
I've fixed this in the beta and master branch.
Could you retest the automatic install script?

**Comment by edwin123456** [comment]
Its working for me ,
Thank you

**Comment by lokonli** [comment]
Fixed
