### ISSUE TITLE
Make dial working for blinds switch

### ISSUE THREAD

**Issue by jahlex** [Dashticz/dashticz#881]
Hi,

Great job with dials but dial type is not working for blinds switch. It would be great to have a dial for this kind of switch. For instance with the status of the blinds (open / closed)  in the middle of the dial (text or icon) and two buttons, up and down, on top and bottom of the dial. 

Thanks.

**Comment by Foxhill67** [comment]
I agree, that would be nice addition!

**Comment by lokonli** [comment]
Implemented with #904 

Please test v3.8.9-beta

**Comment by Foxhill67** [comment]
Works fine, tnxs!

Changing up and down button text also works fine.  One small remark: text in center part is fixed ('Open' or 'Closed'). Could it be easily suppressed? Or also made customizable?

**Comment by lokonli** [comment]
By setting the block parameter 'showvalue' to false the value will not be rendered.

**Comment by Foxhill67** [comment]
Ah of course! Tnxs and keep up the good work!

**Comment by lokonli** [comment]
Implemented in 3.8.10
