### ISSUE TITLE
Publictransport (9292 API down)

### ISSUE THREAD

**Issue by HansieNL** [Dashticz/dashticz#910]
Publictransport block will not load at the moment. Only the message “Loading” is shown.
[https://www.domoticz.com/forum/viewtopic.php?p=284837#p284837](https://www.domoticz.com/forum/viewtopic.php?p=284837#p284837)

**Comment by lokonli** [comment]
Needs some work.
Train info can be obtained via:
https://www.rijdendetreinen.nl/ajax/departures?station=VL

bus/tram/metro info via:
https://v0.ovapi.nl/stopareacode/utrlun

All stopareacodes are listed on:
https://v0.ovapi.nl/stopareacode/

**Comment by lokonli** [comment]
Implemented in 3.8.10
