### ISSUE TITLE
Public Transport : french provider ?

### ISSUE THREAD

**Issue by Diplo95** [Dashticz/dashticz#911]
Hi,
I'm far from having the knowledge you have in API calling/processing. I'd like to know if it would be possible to integrate a french provider in the module. I've made some research, but I don't know what are the information you really need. 

The provider would be Transdev. It seems it provides an API, I can use this way : 
[https://www.transdev-idf.com/horaires-ligne-23/busteni-vers-gare-de-lieusaint-moissy/519-519-695913991-695913977)](https://www.transdev-idf.com/horaires-ligne-23/busteni-vers-gare-de-lieusaint-moissy/519-519-695913991-695913977)
As it is in french, I translate : 
horaires = timetable
ligne 23 = 23 is the name of the bus line (which is the nearest bus stop near my house)
busteni = bus stop name
vers = 'to'
gare de lieusaint moissy = name of terminus

I'm sorry but I haven't the knowledge to test the possibilities of the API. Is it possible to do something with this information  ? What kind of information would you need ?

Thx

**Comment by lokonli** [comment]
The provides link shows a webpage. I need a more detailed description of the API how to obtain the raw data.

**Comment by lokonli** [comment]
No api. Closed
