### ISSUE TITLE
Feature Request: Buienradar monochrome map

### ISSUE THREAD

**Issue by stephanvdplas** [Dashticz/dashticz#912]
I'd like to have the buienradar animated button be displayed as monochrome. Can this be implemented, maybe just like in https://github.com/StefanNienhuis/MMM-Buienradar?

**Comment by lokonli** [comment]
Currently there is no block parameter for this. However, the same effect can be achieved rather easily by adding the following to custom.css:

     [data-id="buien"].dt_block {
         filter: grayscale(100%);
     }

This assumes that you've defined your buienradar block via

blocks['buien'] = {
 ...
}

If there is a huge demand, I may add this as a block parameter as well, but currently it doesn't have the highest priority for me.
