### ISSUE TITLE
Add "Inverted Door Lock" to the Blocks List.

### ISSUE THREAD

**Issue by Ashitaka57** [Dashticz/dashticz#915]
Hello, thanks for the achieved work so far.

here I ask to add a small feature, I can only guess it's a small miss.

The Door Blocks are correctly implemented, but the Inverted Door Block are missing and so they are handled as a On/Off block by default.

In the blocks.js script,

at the line 908, you need to duplicated the "Door Lock" case clause, with a new one
`
case 'Door Lock':
      return getDefaultSwitchBlock(block, 'fas fa-lock', 'fas fa-unlock', buttonimg, language.switches.state_unlocked, language.switches.state_locked );
`

add
`
case 'Door Lock Inverted':
      return getDefaultSwitchBlock(block, 'fas fa-lock', 'fas fa-unlock', buttonimg, language.switches.state_unlocked, language.switches.state_locked );
`
And it would do the trick.

Thanks for reading and upgrading.
Best Regards,

**Comment by lokonli** [comment]
I would expect that the icons and text need to be switched as well. Could you check?
In the mean time I'll prepare the patch.

**Comment by lokonli** [comment]
Added to latest beta.
See PR #913 

Can you test?

**Comment by lokonli** [comment]
Implemented in 3.8.11
