### ISSUE TITLE
No results for Public Transport

### ISSUE THREAD

**Issue by JanvdW304** [Dashticz/dashticz#926]
Since some weeks Dashticz 'Public transport' doesn't show results any more. My Dashticz config looks like
`var publictransport = {}
publictransport.ovinfotrain = { station: 'station-dordrecht', provider: '9292', icon: 'fas fa-train', width:6, results: 6 };
publictransport.ovinfobus = { station: 'dordrecht/bushalte-prof-waterinklaan', provider: '9292-bus', icon: 'fas fa-bus-alt', width:6, results: 8 };`
I found that the locations page for the 9292 service that is mentioned in the Dashticz documentation is not valid any more. It seems that the 9292 API is changed, see https://locaties-api.9292.nl/index.html#/. Probably this causes my problem, but in that case I am wondering why I can't found other issues about this topic. Any suggestions?

**Comment by lokonli** [comment]
9292 API changed indeed. Unfortunately, they don't provide a free API key anymore.

You are using the master branch I assume?
Public transport module has been updated in a recent beta. A new master version will be released soon (this month)

See:
https://www.domoticz.com/forum/viewtopic.php?t=37884

**Comment by JanvdW304** [comment]
Thanks a lot! I'll wait for the update

**Comment by lokonli** [comment]
Solved in v3.9
