### ISSUE TITLE
Rova api key seems to be expired

### ISSUE THREAD

**Issue by BasKloet** [Dashticz/dashticz#938]
Since this weekend I no longer get garbage updates for ROVA. After checking the code to see what URL was used and trying that in the browser, I got the following response:
{"response":"NOK","data":[],"error":"Not valid credentials"}

**Comment by lokonli** [comment]
What is your Dashticz version?
The Rova module was updated in July last year.

Rova is working on my Dashticz system.

What is your zipcode?

**Comment by lokonli** [comment]
For your zipcode Rova indeed doesn't work. (for others it still does)

Good news: I've found an alternative API that seems to work. I'll make a fix.

**Comment by lokonli** [comment]
Fixed in latest beta with #943 
Can you test?

**Comment by BasKloet** [comment]
Thank you, it works like a charm again!
