### ISSUE TITLE
New WorkerTimers code needs a cache clear on android browsers

### ISSUE THREAD

**Issue by BasKloet** [Dashticz/dashticz#944]
First of all, I do not know if this is an actual bug or something that is normal behavior, but after I updated to the latest beta, my dashticz page would not longer load on my Android devices with the following message: "WorkerTimers is not defined".
After clearing the cache in the browsers the problem was solved. 

Possible solutions as far as I can see them:
1. Somehow force the browser to load the correct version of the javascript file(s).
2. Add a note to the release notes telling people to clear their cache if they run into this problem.

**Comment by lokonli** [comment]
Thanks for reporting.
The code contains a mechanism to enforce cache refresh. I've to check why it didn't work this time.

**Comment by lokonli** [comment]
Fixed in #949 3.9.2-beta
