### ISSUE TITLE
Fix Garbage.js for Uden

### ISSUE THREAD

**Issue by evandenbroek** [Dashticz/dashticz#997]
Gemeente Uden is nog Gemeente Maashorst. Remove Uden from Garbage.js and replace with:

      maashorst: {
        handler: getIcalData,
        param:
          'https://www.gemeentemaashorst.nl/inwoners/afval/afvalkalender/' + 
          moment().format('YYYY') +
          '/ics/' +
          zipcode +
          '/' +
          housenumber, 
      },

Also update documentation to remove Uden and add Gemeente Maashorst.

**Comment by lokonli** [comment]
Fixed and updated to deafvalapp in 3.10.0.2
